"""Tests for image fields views."""

from uuid import UUID

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from api.models.fields import ImageCameraCalibrationModel, ImageCameraPose


class ImageCameraCalibrationModelTests(APITestCase):
    """Tests for the ImageCameraCalibrationModel model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.camera_cal = ImageCameraCalibrationModel.objects.create(calibration_model_type="rectilinear air")
        cls.camera_cal.save()
        cls.camera_cal_id = cls.camera_cal.id
        cls.camera_cal_detail = reverse(
            "image-camera-calibration-model-detail", kwargs={"pk": cls.camera_cal_id}
        )  # This will look for the URL pattern named "image-camera-calibration-model-detail" which is automatically generated by the router for the ImageCameraCalibrationModelViewSet and pass the camera_cal  # noqa: E501
        cls.camera_cal_list = reverse(
            "image-camera-calibration-model-list"
        )  # This will look for the URL pattern named "image-camera-calibration-model-list" which is automatically generated by the router for the ImageCameraCalibrationModelViewSet  # noqa: E501

    def test_get_camera_cals(self):
        """Test retrieving camera_cals list."""
        url = self.camera_cal_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["calibration_model_type"], "rectilinear air")

    def test_get_camera_cal_by_id(self):
        """Test retrieving a specific camera_cal by id."""
        url = self.camera_cal_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.camera_cal_id)
        self.assertEqual(response.data["calibration_model_type"], "rectilinear air")

    def test_update_camera_cal(self):
        """Test the PUT endpoint."""
        data = {
            "calibration_model_type": "Updated Test calibration model",
        }
        response = self.client.put(self.camera_cal_detail, data, format="json")
        self.camera_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["calibration_model_type"], self.camera_cal.calibration_model_type)

    def test_delete_camera_cal(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.camera_cal_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageCameraCalibrationModel.objects.count(), 0)

    def test_camera_cal_readonly_fields(self):
        """Test that read-only fields of ImageCameraCalibrationModel cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "calibration_model_type": "Attempted Update",
        }
        response = self.client.put(self.camera_cal_detail, data, format="json")
        self.camera_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.camera_cal_id)
        self.assertEqual(response.data["id"], str(self.camera_cal_id))  # The ID should remain unchanged
        self.assertEqual(data["calibration_model_type"], self.camera_cal.calibration_model_type)

    def test_post_camera_cal(self):
        """Test the POST endpoint."""
        data = {"calibration_model_type": "New Test record"}
        response = self.client.post(self.camera_cal_list, data, format="json")
        camera_cal_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageCameraCalibrationModel.objects.count(), 2)
        camera_cal_instance = ImageCameraCalibrationModel.objects.get(id=camera_cal_id)
        self.assertEqual(camera_cal_instance.calibration_model_type, "New Test record")



class ImageCameraPoseTests(APITestCase):
    """Tests for the ImageCameraPose model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.camera_pose = ImageCameraPose.objects.create(utm_east_north_up_meters=[10.0, 20.0])
        cls.camera_pose.save()
        cls.camera_pose_id = cls.camera_pose.id
        cls.camera_pose_detail = reverse(
            "image-camera-pose-detail", kwargs={"pk": cls.camera_pose_id}
        )  # This will look for the URL pattern named "image-camera-pose-detail" which is automatically generated by the router for the ImageCameraPoseViewSet and pass the camera_pose  # noqa: E501
        cls.camera_pose_list = reverse(
            "image-camera-pose-list"
        )  # This will look for the URL pattern named "image-camera-pose-list" which is automatically generated by the router for the ImageCameraPoseViewSet  # noqa: E501

    def test_get_camera_poses(self):
        """Test retrieving camera_poses list."""
        url = self.camera_pose_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["utm_east_north_up_meters"], [10.0, 20.0])

    def test_get_camera_pose_by_id(self):
        """Test retrieving a specific camera_pose by id."""
        url = self.camera_pose_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.camera_pose_id)
        self.assertEqual(response.data["utm_east_north_up_meters"], [10.0, 20.0])

    def test_update_camera_pose(self):
        """Test the PUT endpoint."""
        data = {
            "utm_east_north_up_meters": [30.0, 40.0],
        }
        response = self.client.put(self.camera_pose_detail, data, format="json")
        self.camera_pose.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["utm_east_north_up_meters"], self.camera_pose.utm_east_north_up_meters)

    def test_delete_camera_pose(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.camera_pose_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageCameraPose.objects.count(), 0)

    def test_camera_pose_readonly_fields(self):
        """Test that read-only fields of ImageCameraPose cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "utm_east_north_up_meters": [1.0,2.0],
        }
        response = self.client.put(self.camera_pose_detail, data, format="json")
        self.camera_pose.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.camera_pose_id)
        self.assertEqual(response.data["id"], str(self.camera_pose_id))  # The ID should remain unchanged
        self.assertEqual(data["utm_east_north_up_meters"], self.camera_pose.utm_east_north_up_meters)

    def test_post_camera_pose(self):
        """Test the POST endpoint."""
        data = {"utm_east_north_up_meters": [50.0, 60.0]}
        response = self.client.post(self.camera_pose_list, data, format="json")
        camera_pose_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageCameraPose.objects.count(), 2)
        camera_pose_instance = ImageCameraPose.objects.get(id=camera_pose_id)
        self.assertEqual(camera_pose_instance.utm_east_north_up_meters, [50.0, 60.0])
