"""Tests for image fields views."""

from uuid import UUID

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from api.models.fields import ImageCameraCalibrationModel


class ImageCameraCalibrationModelTests(APITestCase):
    """Tests for the ImageCameraCalibrationModel model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.camera_cal = ImageCameraCalibrationModel.objects.create(calibration_model_type="rectilinear air")
        cls.camera_cal.save()
        cls.camera_cal_id = cls.camera_cal.id
        cls.camera_cal_detail = reverse(
            "image-camera-calibration-model-detail", kwargs={"pk": cls.camera_cal_id}
        )  # This will look for the URL pattern named "image-camera-calibration-model-detail" which is automatically generated by the router for the ImageCameraCalibrationModelViewSet and pass the camera_cal  # noqa: E501
        cls.camera_cal_list = reverse(
            "image-camera-calibration-model-list"
        )  # This will look for the URL pattern named "image-camera-calibration-model-list" which is automatically generated by the router for the ImageCameraCalibrationModelViewSet  # noqa: E501

    def test_get_camera_cals(self):
        """Test retrieving camera_cals list."""
        url = self.camera_cal_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["calibration_model_type"], "rectilinear air")

    def test_get_camera_cal_by_id(self):
        """Test retrieving a specific camera_cal by id."""
        url = self.camera_cal_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.camera_cal_id)
        self.assertEqual(response.data["calibration_model_type"], "rectilinear air")

    def test_update_camera_cal(self):
        """Test the PUT endpoint."""
        data = {
            "calibration_model_type": "Updated Test calibration model",
        }
        response = self.client.put(self.camera_cal_detail, data, format="json")
        self.camera_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["calibration_model_type"], self.camera_cal.calibration_model_type)


    def test_delete_camera_cal(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.camera_cal_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageCameraCalibrationModel.objects.count(), 0)
