"""Unit tests for annotations endpoints."""

from uuid import UUID

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from api.models.annotation import Annotator


class AnnotatorTests(APITestCase):
    """Tests for the Annotator model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.annotator = Annotator.objects.create(name="Test Annotator")
        cls.annotator.save()
        cls.annotator_id = cls.annotator.id
        cls.annotator_detail = reverse(
            "annotator-detail", kwargs={"pk": cls.annotator_id}
        )  # This will look for the URL pattern named "annotator-detail" which is automatically generated by the router for the AnnotatorViewSet and pass the annotator  # noqa: E501
        cls.annotator_list = reverse(
            "annotator-list"
        )  # This will look for the URL pattern named "annotator-list" which is automatically generated by the router for the AnnotatorViewSet  # noqa: E501

    def test_get_annotators(self):
        """Test retrieving annotators list."""
        url = self.annotator_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Annotator")

    def test_get_annotator_detail_by_id(self):
        """Test retrieving a specific annotator."""
        url = self.annotator_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.annotator_id)
        self.assertEqual(response.data["name"], "Test Annotator")

    def test_post_annotator(self):
        """Test the POST /annotator/ endpoint."""
        response = self.client.post(self.annotator_list, {"name": "New Test Annotator"}, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Annotator.objects.count(), 2)
        self.assertEqual(response.data["name"], "New Test Annotator")

    def test_put_annotator(self):
        """Test the PUT /annotator/{id}/ endpoint."""
        response = self.client.put(self.annotator_detail, {"name": "Updated Test Annotator"}, format="json")
        self.annotator.refresh_from_db()  # Refresh the annotator instance to get the updated values from the database
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["name"], self.annotator.name)

    def test_readonly_annotator_fields(self):
        """Test that read-only fields cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.annotator_detail, data, format="json")
        self.annotator.refresh_from_db()  # Refresh the annotator instance to get the updated values from the database
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.annotator_id)
        self.assertEqual(response.data["id"], str(self.annotator_id))  # The ID should remain unchanged
        self.assertEqual(response.data["name"], self.annotator.name)

    def test_delete_annotator(self):
        """Test the DELETE /annotator/{id}/ endpoint."""
        response = self.client.delete(self.annotator_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Annotator.objects.count(), 0)
