"""Tests for fields views."""

from uuid import UUID

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from api.models.fields import PI, Context, Creator


class CreatorTests(APITestCase):
    """Tests for the Creator model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.creator = Creator.objects.create(name="Test Creator", uri="http://example.com/creator")
        cls.creator.save()
        cls.creator_id = cls.creator.id
        cls.creator_detail = reverse("creator-detail", kwargs={"pk": cls.creator_id}) #This will look for the URL pattern named "creator-detail" which is automatically generated by the router for the CreatorViewSet and pass the creator  # noqa: E501
        cls.creator_list = reverse("creator-list") #This will look for the URL pattern named "creator-list" which is automatically generated by the router for the CreatorViewSet  # noqa: E501


    def test_get_creators(self):
        """Test retrieving creators list."""
        url = self.creator_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Creator")
        self.assertEqual(response.data[0]["uri"], "http://example.com/creator")

    def test_get_creator_detail(self):
        """Test retrieving a specific creator."""
        url = self.creator_detail
        print(f"Testing URL: {url}")  # Debugging line to check the URL being tested
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.creator_id)
        self.assertEqual(response.data["name"], "Test Creator")
        self.assertEqual(response.data["uri"], "http://example.com/creator")

    def test_post_creator(self):
        """Test the POST /creators/ endpoint."""
        data = {
            "name": "New Test Creator",
            "uri": "http://test.com"
        }
        response = self.client.post(self.creator_list, data, format='json')

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Creator.objects.count(), 2)
        self.assertEqual(response.data['name'], "New Test Creator")
        self.assertEqual(response.data['uri'], "http://test.com")

    def test_put_creator(self):
        """Test the PUT /creators/{id}/ endpoint."""
        data = {
            "name": "Updated Test Creator",
            "uri": "http://updated.com"
        }
        response = self.client.put(self.creator_detail, data, format='json')
        self.creator.refresh_from_db() # Refresh the creator instance to get the updated values from the database
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data['name'], self.creator.name)
        self.assertEqual(data['uri'], self.creator.uri)

    def test_readonly_creator_fields(self):
        """Test that read-only fields cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.creator_detail, data, format='json')
        self.creator.refresh_from_db() # Refresh the creator instance to get the updated values from the database
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.creator_id)
        self.assertEqual(response.data['id'], str(self.creator_id)) # The ID should remain unchanged
        self.assertEqual(response.data['name'], self.creator.name)


    def test_delete_creator(self):
        """Test the DELETE /creators/{id}/ endpoint."""
        response = self.client.delete(self.creator_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Creator.objects.count(), 0)


class ContextTests(APITestCase):
    """Tests for the Context model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.context = Context.objects.create(name="Test Context", uri="http://test.com/context")
        cls.context.save()
        cls.context_id = cls.context.id
        cls.context_detail = reverse("context-detail", kwargs={"pk": cls.context_id}) #This will look for the URL pattern named "context-detail" which is automatically generated by the router for the ContextViewSet and pass the context  # noqa: E501
        cls.context_list = reverse("context-list") #This will look for the URL pattern named "context-list" which is automatically generated by the router for the ContextViewSet  # noqa: E501

    def test_get_contexts(self):
        """Test retrieving contexts list."""
        url = self.context_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Context")
        self.assertEqual(response.data[0]["uri"], "http://test.com/context")

    def test_get_context_by_id(self):
        """Test retrieving a specific context by id /api/contexts/{id}/."""
        url = self.context_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.context_id)
        self.assertEqual(response.data["name"], "Test Context")
        self.assertEqual(response.data["uri"], "http://test.com/context")

    def test_update_context(self):
        """Test the PUT /contexts/{id}/ endpoint."""
        data = {
            "name": "Updated Test Context",
        }
        response = self.client.put(self.context_detail, data, format='json')
        self.context.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data['name'], self.context.name)

    def test_context_readonly_fields(self):
        """Test that read-only fields of Context cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.context_detail, data, format='json')
        self.context.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.context_id)
        self.assertEqual(response.data['id'], str(self.context_id)) # The ID should remain unchanged
        self.assertEqual(response.data['name'], self.context.name)


    def test_delete_context(self):
        """Test the DELETE /contexts/{id}/ endpoint."""
        response = self.client.delete(self.context_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Context.objects.count(), 0)

    def test_post_context(self):
        """Test the POST /contexts/ endpoint."""
        data = {
            "name": "New Test Context",
            "uri": "http://test.com/context"
        }
        response = self.client.post(self.context_list, data, format='json')
        context_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Context.objects.count(), 2)
        context_instance = Context.objects.get(id=context_id)
        self.assertEqual(context_instance.name, "New Test Context")


class PITests(APITestCase):
    """Tests for the PI model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.pi = PI.objects.create(name="Test PI", uri="http://test.com/pi")
        cls.pi.save()
        cls.pi_id = cls.pi.id
        cls.pi_detail = reverse("pi-detail", kwargs={"pk": cls.pi_id}) #This will look for the URL pattern named "pi-detail" which is automatically generated by the router for the PIViewSet and pass the pi  # noqa: E501
        cls.pi_list = reverse("pi-list") #This will look for the URL pattern named "pi-list" which is automatically generated by the router for the PIViewSet  # noqa: E501

    def test_get_pis(self):
        """Test retrieving pis list using /api/pis/."""
        url = self.pi_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test PI")
        self.assertEqual(response.data[0]["uri"], "http://test.com/pi")

    def test_get_pi_by_id(self):
        """Test retrieving a specific pi by id /api/pis/{id}/."""
        url = self.pi_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.pi_id)
        self.assertEqual(response.data["name"], "Test PI")
        self.assertEqual(response.data["uri"], "http://test.com/pi")

    def test_update_pi(self):
        """Test the PUT /pis/{id}/ endpoint."""
        data = {
            "name": "Updated Test PI",
        }
        response = self.client.put(self.pi_detail, data, format='json')
        self.pi.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data['name'], self.pi.name)

    def test_pi_readonly_fields(self):
        """Test that read-only fields of PI cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.pi_detail, data, format='json')
        self.pi.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.pi_id)
        self.assertEqual(response.data['id'], str(self.pi_id)) # The ID should remain unchanged
        self.assertEqual(data['name'], self.pi.name)

    def test_delete_pi(self):
        """Test the DELETE /api/pis/{id}/ endpoint."""
        response = self.client.delete(self.pi_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(PI.objects.count(), 0)

    def test_post_pi(self):
        """Test the POST api/pis/ endpoint."""
        data = {
            "name": "New Test PI",
            "uri": "http://test.com/pi"
        }
        response = self.client.post(self.pi_list, data, format='json')
        pi_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(PI.objects.count(), 2)
        pi_instance = PI.objects.get(id=pi_id)
        self.assertEqual(pi_instance.name, "New Test PI")
