"""Tests for image fields views."""

from uuid import UUID

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from api.models.fields import (
    ImageCameraCalibrationModel,
    ImageCameraHousingViewport,
    ImageCameraPose,
    ImageDomeportParameter,
    ImageFlatportParameter,
    ImagePhotometricCalibration,
)


class ImageCameraCalibrationModelTests(APITestCase):
    """Tests for the ImageCameraCalibrationModel model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.camera_cal = ImageCameraCalibrationModel.objects.create(calibration_model_type="rectilinear air")
        cls.camera_cal.save()
        cls.camera_cal_id = cls.camera_cal.id
        cls.camera_cal_detail = reverse(
            "image-camera-calibration-model-detail", kwargs={"pk": cls.camera_cal_id}
        )  # This will look for the URL pattern named "image-camera-calibration-model-detail" which is automatically generated by the router for the ImageCameraCalibrationModelViewSet and pass the camera_cal  # noqa: E501
        cls.camera_cal_list = reverse(
            "image-camera-calibration-model-list"
        )  # This will look for the URL pattern named "image-camera-calibration-model-list" which is automatically generated by the router for the ImageCameraCalibrationModelViewSet  # noqa: E501

    def test_get_camera_cals(self):
        """Test retrieving camera_cals list."""
        url = self.camera_cal_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["calibration_model_type"], "rectilinear air")

    def test_get_camera_cal_by_id(self):
        """Test retrieving a specific camera_cal by id."""
        url = self.camera_cal_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.camera_cal_id)
        self.assertEqual(response.data["calibration_model_type"], "rectilinear air")

    def test_update_camera_cal(self):
        """Test the PUT endpoint."""
        data = {
            "calibration_model_type": "Updated Test calibration model",
        }
        response = self.client.put(self.camera_cal_detail, data, format="json")
        self.camera_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["calibration_model_type"], self.camera_cal.calibration_model_type)

    def test_delete_camera_cal(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.camera_cal_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageCameraCalibrationModel.objects.count(), 0)

    def test_camera_cal_readonly_fields(self):
        """Test that read-only fields of ImageCameraCalibrationModel cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "calibration_model_type": "Attempted Update",
        }
        response = self.client.put(self.camera_cal_detail, data, format="json")
        self.camera_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.camera_cal_id)
        self.assertEqual(response.data["id"], str(self.camera_cal_id))  # The ID should remain unchanged
        self.assertEqual(data["calibration_model_type"], self.camera_cal.calibration_model_type)

    def test_post_camera_cal(self):
        """Test the POST endpoint."""
        data = {"calibration_model_type": "New Test record"}
        response = self.client.post(self.camera_cal_list, data, format="json")
        camera_cal_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageCameraCalibrationModel.objects.count(), 2)
        camera_cal_instance = ImageCameraCalibrationModel.objects.get(id=camera_cal_id)
        self.assertEqual(camera_cal_instance.calibration_model_type, "New Test record")


class ImageCameraPoseTests(APITestCase):
    """Tests for the ImageCameraPose model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.camera_pose = ImageCameraPose.objects.create(utm_east_north_up_meters=[10.0, 20.0])
        cls.camera_pose.save()
        cls.camera_pose_id = cls.camera_pose.id
        cls.camera_pose_detail = reverse(
            "image-camera-pose-detail", kwargs={"pk": cls.camera_pose_id}
        )  # This will look for the URL pattern named "image-camera-pose-detail" which is automatically generated by the router for the ImageCameraPoseViewSet and pass the camera_pose  # noqa: E501
        cls.camera_pose_list = reverse(
            "image-camera-pose-list"
        )  # This will look for the URL pattern named "image-camera-pose-list" which is automatically generated by the router for the ImageCameraPoseViewSet  # noqa: E501

    def test_get_camera_poses(self):
        """Test retrieving camera_poses list."""
        url = self.camera_pose_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["utm_east_north_up_meters"], [10.0, 20.0])

    def test_get_camera_pose_by_id(self):
        """Test retrieving a specific camera_pose by id."""
        url = self.camera_pose_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.camera_pose_id)
        self.assertEqual(response.data["utm_east_north_up_meters"], [10.0, 20.0])

    def test_update_camera_pose(self):
        """Test the PUT endpoint."""
        data = {
            "utm_east_north_up_meters": [30.0, 40.0],
        }
        response = self.client.put(self.camera_pose_detail, data, format="json")
        self.camera_pose.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["utm_east_north_up_meters"], self.camera_pose.utm_east_north_up_meters)

    def test_delete_camera_pose(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.camera_pose_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageCameraPose.objects.count(), 0)

    def test_camera_pose_readonly_fields(self):
        """Test that read-only fields of ImageCameraPose cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "utm_east_north_up_meters": [1.0, 2.0],
        }
        response = self.client.put(self.camera_pose_detail, data, format="json")
        self.camera_pose.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.camera_pose_id)
        self.assertEqual(response.data["id"], str(self.camera_pose_id))  # The ID should remain unchanged
        self.assertEqual(data["utm_east_north_up_meters"], self.camera_pose.utm_east_north_up_meters)

    def test_post_camera_pose(self):
        """Test the POST endpoint."""
        data = {"utm_east_north_up_meters": [50.0, 60.0]}
        response = self.client.post(self.camera_pose_list, data, format="json")
        camera_pose_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageCameraPose.objects.count(), 2)
        camera_pose_instance = ImageCameraPose.objects.get(id=camera_pose_id)
        self.assertEqual(camera_pose_instance.utm_east_north_up_meters, [50.0, 60.0])


class ImageDomeportParameterTests(APITestCase):
    """Tests for the ImageDomeportParameter model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.domeport_param = ImageDomeportParameter.objects.create(extra_description="Test domeport parameter")
        cls.domeport_param.save()
        cls.domeport_param_id = cls.domeport_param.id
        cls.domeport_param_detail = reverse(
            "image-domeport-parameter-detail", kwargs={"pk": cls.domeport_param_id}
        )  # This will look for the URL pattern named "image-domeport-parameter-detail" which is automatically generated by the router for the ImageDomeportParameterViewSet and pass the domeport_param  # noqa: E501
        cls.domeport_param_list = reverse(
            "image-domeport-parameter-list"
        )  # This will look for the URL pattern named "image-domeport-parameter-list" which is automatically generated by the router for the ImageDomeportParameterViewSet  # noqa: E501

    def test_get_domeport_params(self):
        """Test retrieving domeport_params list."""
        url = self.domeport_param_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["extra_description"], "Test domeport parameter")

    def test_get_domeport_param_by_id(self):
        """Test retrieving a specific domeport_param by id."""
        url = self.domeport_param_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.domeport_param_id)
        self.assertEqual(response.data["extra_description"], "Test domeport parameter")

    def test_update_domeport_param(self):
        """Test the PUT endpoint."""
        data = {
            "extra_description": "Updated domeport",
        }
        response = self.client.put(self.domeport_param_detail, data, format="json")
        self.domeport_param.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["extra_description"], self.domeport_param.extra_description)

    def test_delete_domeport_param(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.domeport_param_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageDomeportParameter.objects.count(), 0)

    def test_domeport_param_readonly_fields(self):
        """Test that read-only fields of ImageDomeportParameter cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "extra_description": "Updated domeport",
        }
        response = self.client.put(self.domeport_param_detail, data, format="json")
        self.domeport_param.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.domeport_param_id)
        self.assertEqual(response.data["id"], str(self.domeport_param_id))  # The ID should remain unchanged
        self.assertEqual(data["extra_description"], self.domeport_param.extra_description)

    def test_post_domeport_param(self):
        """Test the POST endpoint."""
        data = {"extra_description": "New domeport parameter"}
        response = self.client.post(self.domeport_param_list, data, format="json")
        domeport_param_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageDomeportParameter.objects.count(), 2)
        domeport_param_instance = ImageDomeportParameter.objects.get(id=domeport_param_id)
        self.assertEqual(domeport_param_instance.extra_description, "New domeport parameter")


class ImageFlatportParameterTests(APITestCase):
    """Tests for the ImageFlatportParameter model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.flatport_param = ImageFlatportParameter.objects.create(extra_description="Test flatport parameter")
        cls.flatport_param.save()
        cls.flatport_param_id = cls.flatport_param.id
        cls.flatport_param_detail = reverse(
            "image-flatport-parameter-detail", kwargs={"pk": cls.flatport_param_id}
        )  # This will look for the URL pattern named "image-flatport-parameter-detail" which is automatically generated by the router for the ImageFlatportParameterViewSet and pass the flatport_param  # noqa: E501
        cls.flatport_param_list = reverse(
            "image-flatport-parameter-list"
        )  # This will look for the URL pattern named "image-flatport-parameter-list" which is automatically generated by the router for the ImageFlatportParameterViewSet  # noqa: E501

    def test_get_flatport_params(self):
        """Test retrieving flatport_params list."""
        url = self.flatport_param_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["extra_description"], "Test flatport parameter")

    def test_get_flatport_param_by_id(self):
        """Test retrieving a specific flatport_param by id."""
        url = self.flatport_param_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.flatport_param_id)
        self.assertEqual(response.data["extra_description"], "Test flatport parameter")

    def test_update_flatport_param(self):
        """Test the PUT endpoint."""
        data = {
            "extra_description": "Updated flatport parameter",
        }
        response = self.client.put(self.flatport_param_detail, data, format="json")
        self.flatport_param.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["extra_description"], self.flatport_param.extra_description)

    def test_delete_flatport_param(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.flatport_param_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageFlatportParameter.objects.count(), 0)

    def test_flatport_param_readonly_fields(self):
        """Test that read-only fields of ImageFlatportParameter cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "extra_description": "Updated flatport parameter",
        }
        response = self.client.put(self.flatport_param_detail, data, format="json")
        self.flatport_param.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.flatport_param_id)
        self.assertEqual(response.data["id"], str(self.flatport_param_id))  # The ID should remain unchanged
        self.assertEqual(data["extra_description"], self.flatport_param.extra_description)

    def test_post_flatport_param(self):
        """Test the POST endpoint."""
        data = {"extra_description": "New flatport parameter"}
        response = self.client.post(self.flatport_param_list, data, format="json")
        flatport_param_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageFlatportParameter.objects.count(), 2)
        flatport_param_instance = ImageFlatportParameter.objects.get(id=flatport_param_id)
        self.assertEqual(flatport_param_instance.extra_description, "New flatport parameter")


class ImageCameraHousingViewportTests(APITestCase):
    """Tests for the ImageCameraHousingViewport model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.housing_param = ImageCameraHousingViewport.objects.create(extra_description="Test housing parameter")
        cls.housing_param.save()
        cls.housing_param_id = cls.housing_param.id
        cls.housing_param_detail = reverse(
            "image-camera-housing-viewport-detail", kwargs={"pk": cls.housing_param_id}
        )  # This will look for the URL pattern named "image-camera-housing-viewport-detail" which is automatically generated by the router for the ImageCameraHousingViewportViewSet and pass the housing_param  # noqa: E501
        cls.housing_param_list = reverse(
            "image-camera-housing-viewport-list"
        )  # This will look for the URL pattern named "image-camera-housing-viewport-list" which is automatically generated by the router for the ImageCameraHousingViewportViewSet  # noqa: E501

    def test_get_housing_params(self):
        """Test retrieving housing_params list."""
        url = self.housing_param_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["extra_description"], "Test housing parameter")

    def test_get_housing_param_by_id(self):
        """Test retrieving a specific housing_param by id."""
        url = self.housing_param_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.housing_param_id)
        self.assertEqual(response.data["extra_description"], "Test housing parameter")

    def test_update_housing_param(self):
        """Test the PUT endpoint."""
        data = {
            "extra_description": "Updated housing parameter",
        }
        response = self.client.put(self.housing_param_detail, data, format="json")
        self.housing_param.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["extra_description"], self.housing_param.extra_description)

    def test_delete_housing_param(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.housing_param_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImageCameraHousingViewport.objects.count(), 0)

    def test_housing_param_readonly_fields(self):
        """Test that read-only fields of ImageCameraHousingViewport cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "extra_description": "Updated housing parameter",
        }
        response = self.client.put(self.housing_param_detail, data, format="json")
        self.housing_param.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.housing_param_id)
        self.assertEqual(response.data["id"], str(self.housing_param_id))  # The ID should remain unchanged
        self.assertEqual(data["extra_description"], self.housing_param.extra_description)

    def test_post_housing_param(self):
        """Test the POST endpoint."""
        data = {"extra_description": "New housing parameter"}
        response = self.client.post(self.housing_param_list, data, format="json")
        housing_param_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImageCameraHousingViewport.objects.count(), 2)
        housing_param_instance = ImageCameraHousingViewport.objects.get(id=housing_param_id)
        self.assertEqual(housing_param_instance.extra_description, "New housing parameter")


class ImagePhotometricCalibrationTests(APITestCase):
    """Tests for the ImagePhotometricCalibration model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.photometric_cal = ImagePhotometricCalibration.objects.create(
            sequence_illumination_type="constant artificial"
        )
        cls.photometric_cal.save()
        cls.photometric_cal_id = cls.photometric_cal.id
        cls.photometric_cal_detail = reverse(
            "image-photometric-calibration-detail", kwargs={"pk": cls.photometric_cal_id}
        )  # This will look for the URL pattern named "image-photometric-calibration-detail" which is automatically generated by the router for the ImagePhotometricCalibrationViewSet and pass the photometric_cal  # noqa: E501
        cls.photometric_cal_list = reverse(
            "image-photometric-calibration-list"
        )  # This will look for the URL pattern named "image-photometric-calibration-list" which is automatically generated by the router for the ImagePhotometricCalibrationViewSet  # noqa: E501

    def test_get_photometric_cals(self):
        """Test retrieving photometric_cals list."""
        url = self.photometric_cal_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["sequence_illumination_type"], "constant artificial")

    def test_get_photometric_cal_by_id(self):
        """Test retrieving a specific photometric_cal by id."""
        url = self.photometric_cal_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.photometric_cal_id)
        self.assertEqual(response.data["sequence_illumination_type"], "constant artificial")

    def test_update_photometric_cal(self):
        """Test the PUT endpoint."""
        data = {
            "sequence_illumination_type": "sunlight",
        }
        response = self.client.put(self.photometric_cal_detail, data, format="json")
        self.photometric_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["sequence_illumination_type"], self.photometric_cal.sequence_illumination_type)

    def test_delete_photometric_cal(self):
        """Test the DELETE endpoint."""
        response = self.client.delete(self.photometric_cal_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(ImagePhotometricCalibration.objects.count(), 0)

    def test_photometric_cal_readonly_fields(self):
        """Test that read-only fields of ImagePhotometricCalibration cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "sequence_illumination_type": "sunlight",
        }
        response = self.client.put(self.photometric_cal_detail, data, format="json")
        self.photometric_cal.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.photometric_cal_id)
        self.assertEqual(response.data["id"], str(self.photometric_cal_id))  # The ID should remain unchanged
        self.assertEqual(data["sequence_illumination_type"], self.photometric_cal.sequence_illumination_type)

    def test_post_photometric_cal(self):
        """Test the POST endpoint."""
        data = {"sequence_illumination_type": "mixed"}
        response = self.client.post(self.photometric_cal_list, data, format="json")
        photometric_cal_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ImagePhotometricCalibration.objects.count(), 2)
        photometric_cal_instance = ImagePhotometricCalibration.objects.get(id=photometric_cal_id)
        self.assertEqual(photometric_cal_instance.sequence_illumination_type, "mixed")
