"""Tests for fields views."""

from uuid import UUID

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from api.models.fields import PI, Context, Creator, Event, License, Platform, Project, RelatedMaterial, Sensor


class CreatorTests(APITestCase):
    """Tests for the Creator model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.creator = Creator.objects.create(name="Test Creator", uri="http://example.com/creator")
        cls.creator.save()
        cls.creator_id = cls.creator.id
        cls.creator_detail = reverse(
            "creator-detail", kwargs={"pk": cls.creator_id}
        )  # This will look for the URL pattern named "creator-detail" which is automatically generated by the router for the CreatorViewSet and pass the creator  # noqa: E501
        cls.creator_list = reverse(
            "creator-list"
        )  # This will look for the URL pattern named "creator-list" which is automatically generated by the router for the CreatorViewSet  # noqa: E501

    def test_get_creators(self):
        """Test retrieving creators list."""
        url = self.creator_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Creator")
        self.assertEqual(response.data[0]["uri"], "http://example.com/creator")

    def test_get_creator_detail(self):
        """Test retrieving a specific creator."""
        url = self.creator_detail
        print(f"Testing URL: {url}")  # Debugging line to check the URL being tested
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.creator_id)
        self.assertEqual(response.data["name"], "Test Creator")
        self.assertEqual(response.data["uri"], "http://example.com/creator")

    def test_post_creator(self):
        """Test the POST /creator/ endpoint."""
        data = {"name": "New Test Creator", "uri": "http://test.com"}
        response = self.client.post(self.creator_list, data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Creator.objects.count(), 2)
        self.assertEqual(response.data["name"], "New Test Creator")
        self.assertEqual(response.data["uri"], "http://test.com")

    def test_put_creator(self):
        """Test the PUT /creator/{id}/ endpoint."""
        data = {"name": "Updated Test Creator", "uri": "http://updated.com"}
        response = self.client.put(self.creator_detail, data, format="json")
        self.creator.refresh_from_db()  # Refresh the creator instance to get the updated values from the database
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.creator.name)
        self.assertEqual(data["uri"], self.creator.uri)

    def test_readonly_creator_fields(self):
        """Test that read-only fields cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.creator_detail, data, format="json")
        self.creator.refresh_from_db()  # Refresh the creator instance to get the updated values from the database
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.creator_id)
        self.assertEqual(response.data["id"], str(self.creator_id))  # The ID should remain unchanged
        self.assertEqual(response.data["name"], self.creator.name)

    def test_delete_creator(self):
        """Test the DELETE /creator/{id}/ endpoint."""
        response = self.client.delete(self.creator_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Creator.objects.count(), 0)


class ContextTests(APITestCase):
    """Tests for the Context model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.context = Context.objects.create(name="Test Context", uri="http://test.com/context")
        cls.context.save()
        cls.context_id = cls.context.id
        cls.context_detail = reverse(
            "context-detail", kwargs={"pk": cls.context_id}
        )  # This will look for the URL pattern named "context-detail" which is automatically generated by the router for the ContextViewSet and pass the context  # noqa: E501
        cls.context_list = reverse(
            "context-list"
        )  # This will look for the URL pattern named "context-list" which is automatically generated by the router for the ContextViewSet  # noqa: E501

    def test_get_contexts(self):
        """Test retrieving contexts list."""
        url = self.context_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Context")
        self.assertEqual(response.data[0]["uri"], "http://test.com/context")

    def test_get_context_by_id(self):
        """Test retrieving a specific context by id /api/context/{id}/."""
        url = self.context_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.context_id)
        self.assertEqual(response.data["name"], "Test Context")
        self.assertEqual(response.data["uri"], "http://test.com/context")

    def test_update_context(self):
        """Test the PUT /context/{id}/ endpoint."""
        data = {
            "name": "Updated Test Context",
        }
        response = self.client.put(self.context_detail, data, format="json")
        self.context.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.context.name)

    def test_context_readonly_fields(self):
        """Test that read-only fields of Context cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.context_detail, data, format="json")
        self.context.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.context_id)
        self.assertEqual(response.data["id"], str(self.context_id))  # The ID should remain unchanged
        self.assertEqual(response.data["name"], self.context.name)

    def test_delete_context(self):
        """Test the DELETE /context/{id}/ endpoint."""
        response = self.client.delete(self.context_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Context.objects.count(), 0)

    def test_post_context(self):
        """Test the POST /context/ endpoint."""
        data = {"name": "New Test Context", "uri": "http://test.com/context"}
        response = self.client.post(self.context_list, data, format="json")
        context_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Context.objects.count(), 2)
        context_instance = Context.objects.get(id=context_id)
        self.assertEqual(context_instance.name, "New Test Context")


class PITests(APITestCase):
    """Tests for the PI model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.pi = PI.objects.create(name="Test PI", uri="http://test.com/pi")
        cls.pi.save()
        cls.pi_id = cls.pi.id
        cls.pi_detail = reverse(
            "pi-detail", kwargs={"pk": cls.pi_id}
        )  # This will look for the URL pattern named "pi-detail" which is automatically generated by the router for the PIViewSet and pass the pi  # noqa: E501
        cls.pi_list = reverse(
            "pi-list"
        )  # This will look for the URL pattern named "pi-list" which is automatically generated by the router for the PIViewSet  # noqa: E501

    def test_get_pis(self):
        """Test retrieving pis list using /api/pi/."""
        url = self.pi_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test PI")
        self.assertEqual(response.data[0]["uri"], "http://test.com/pi")

    def test_get_pi_by_id(self):
        """Test retrieving a specific pi by id /api/pi/{id}/."""
        url = self.pi_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.pi_id)
        self.assertEqual(response.data["name"], "Test PI")
        self.assertEqual(response.data["uri"], "http://test.com/pi")

    def test_update_pi(self):
        """Test the PUT /pi/{id}/ endpoint."""
        data = {
            "name": "Updated Test PI",
        }
        response = self.client.put(self.pi_detail, data, format="json")
        self.pi.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.pi.name)

    def test_pi_readonly_fields(self):
        """Test that read-only fields of PI cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.pi_detail, data, format="json")
        self.pi.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.pi_id)
        self.assertEqual(response.data["id"], str(self.pi_id))  # The ID should remain unchanged
        self.assertEqual(data["name"], self.pi.name)

    def test_delete_pi(self):
        """Test the DELETE /api/pi/{id}/ endpoint."""
        response = self.client.delete(self.pi_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(PI.objects.count(), 0)

    def test_post_pi(self):
        """Test the POST api/pi/ endpoint."""
        data = {"name": "New Test PI", "uri": "http://test.com/pi"}
        response = self.client.post(self.pi_list, data, format="json")
        pi_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(PI.objects.count(), 2)
        pi_instance = PI.objects.get(id=pi_id)
        self.assertEqual(pi_instance.name, "New Test PI")


class EventTests(APITestCase):
    """Tests for the Event model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.event = Event.objects.create(name="Test Event", uri="http://test.com/event")
        cls.event.save()
        cls.event_id = cls.event.id
        cls.event_detail = reverse(
            "event-detail", kwargs={"pk": cls.event_id}
        )  # This will look for the URL pattern named "event-detail" which is automatically generated by the router for the EventViewSet and pass the event  # noqa: E501
        cls.event_list = reverse(
            "event-list"
        )  # This will look for the URL pattern named "event-list" which is automatically generated by the router for the EventViewSet  # noqa: E501

    def test_get_events(self):
        """Test retrieving events list using /api/event/."""
        url = self.event_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Event")
        self.assertEqual(response.data[0]["uri"], "http://test.com/event")

    def test_get_event_by_id(self):
        """Test retrieving a specific event by id /api/events/{id}/."""
        url = self.event_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.event_id)
        self.assertEqual(response.data["name"], "Test Event")
        self.assertEqual(response.data["uri"], "http://test.com/event")

    def test_update_event(self):
        """Test the PUT /event/{id}/ endpoint."""
        data = {
            "name": "Updated Test Event",
        }
        response = self.client.put(self.event_detail, data, format="json")
        self.event.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.event.name)

    def test_event_readonly_fields(self):
        """Test that read-only fields of Event cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.event_detail, data, format="json")
        self.event.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.event_id)
        self.assertEqual(response.data["id"], str(self.event_id))  # The ID should remain unchanged
        self.assertEqual(data["name"], self.event.name)

    def test_post_event(self):
        """Test the POST api/event/ endpoint."""
        data = {"name": "New Test Event", "uri": "http://test.com/event"}
        response = self.client.post(self.event_list, data, format="json")
        event_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Event.objects.count(), 2)
        event_instance = Event.objects.get(id=event_id)
        self.assertEqual(event_instance.name, "New Test Event")

    def test_delete_event(self):
        """Test the DELETE /api/event/{id}/ endpoint."""
        response = self.client.delete(self.event_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Event.objects.count(), 0)


class LicenseTests(APITestCase):
    """Tests for the License model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.license = License.objects.create(name="Test License", uri="http://test.com/license")
        cls.license.save()
        cls.license_id = cls.license.id
        cls.license_detail = reverse(
            "license-detail", kwargs={"pk": cls.license_id}
        )  # This will look for the URL pattern named "license-detail" which is automatically generated by the router for the LicenseViewSet and pass the license  # noqa: E501
        cls.license_list = reverse(
            "license-list"
        )  # This will look for the URL pattern named "license-list" which is automatically generated by the router for the LicenseViewSet  # noqa: E501

    def test_get_licenses(self):
        """Test retrieving licenses list using /api/license/."""
        url = self.license_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test License")
        self.assertEqual(response.data[0]["uri"], "http://test.com/license")

    def test_get_license_by_id(self):
        """Test retrieving a specific license by id /api/license/{id}/."""
        url = self.license_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.license_id)
        self.assertEqual(response.data["name"], "Test License")
        self.assertEqual(response.data["uri"], "http://test.com/license")

    def test_update_license(self):
        """Test the PUT /license/{id}/ endpoint."""
        data = {
            "name": "Updated Test License",
        }
        response = self.client.put(self.license_detail, data, format="json")
        self.license.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.license.name)

    def test_license_readonly_fields(self):
        """Test that read-only fields of License cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.license_detail, data, format="json")
        self.license.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.license_id)
        self.assertEqual(response.data["id"], str(self.license_id))  # The ID should remain unchanged
        self.assertEqual(data["name"], self.license.name)

    def test_post_license(self):
        """Test the POST api/license/ endpoint."""
        data = {"name": "New Test License", "uri": "http://test.com/license"}
        response = self.client.post(self.license_list, data, format="json")
        license_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(License.objects.count(), 2)
        license_instance = License.objects.get(id=license_id)
        self.assertEqual(license_instance.name, "New Test License")

    def test_delete_license(self):
        """Test the DELETE /api/license/{id}/ endpoint."""
        response = self.client.delete(self.license_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(License.objects.count(), 0)


class PlatformTests(APITestCase):
    """Tests for the Platform model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.platform = Platform.objects.create(name="Test Platform", uri="http://test.com/platform")
        cls.platform.save()
        cls.platform_id = cls.platform.id
        cls.platform_detail = reverse(
            "platform-detail", kwargs={"pk": cls.platform_id}
        )  # This will look for the URL pattern named "platform-detail" which is automatically generated by the router for the PlatformViewSet and pass the platform  # noqa: E501
        cls.platform_list = reverse(
            "platform-list"
        )  # This will look for the URL pattern named "platform-list" which is automatically generated by the router for the PlatformViewSet  # noqa: E501

    def test_get_platforms(self):
        """Test retrieving platforms list using /api/platform/."""
        url = self.platform_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Platform")
        self.assertEqual(response.data[0]["uri"], "http://test.com/platform")

    def test_get_platform_by_id(self):
        """Test retrieving a specific platform by id /api/platform/{id}/."""
        url = self.platform_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.platform_id)
        self.assertEqual(response.data["name"], "Test Platform")
        self.assertEqual(response.data["uri"], "http://test.com/platform")

    def test_update_platform(self):
        """Test the PUT /platform/{id}/ endpoint."""
        data = {
            "name": "Updated Test Platform",
        }
        response = self.client.put(self.platform_detail, data, format="json")
        self.platform.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.platform.name)

    def test_platform_readonly_fields(self):
        """Test that read-only fields of Platform cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.platform_detail, data, format="json")
        self.platform.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.platform_id)
        self.assertEqual(response.data["id"], str(self.platform_id))  # The ID should remain unchanged
        self.assertEqual(data["name"], self.platform.name)

    def test_post_platform(self):
        """Test the POST api/platform/ endpoint."""
        data = {"name": "New Test Platform", "uri": "http://test.com/platform"}
        response = self.client.post(self.platform_list, data, format="json")
        platform_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Platform.objects.count(), 2)
        platform_instance = Platform.objects.get(id=platform_id)
        self.assertEqual(platform_instance.name, "New Test Platform")

    def test_delete_platform(self):
        """Test the DELETE /api/platform/{id}/ endpoint."""
        response = self.client.delete(self.platform_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Platform.objects.count(), 0)


class ProjectTests(APITestCase):
    """Tests for the Project model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.project = Project.objects.create(name="Test Project", uri="http://test.com/project")
        cls.project.save()
        cls.project_id = cls.project.id
        cls.project_detail = reverse(
            "project-detail", kwargs={"pk": cls.project_id}
        )  # This will look for the URL pattern named "project-detail" which is automatically generated by the router for the ProjectViewSet and pass the project  # noqa: E501
        cls.project_list = reverse(
            "project-list"
        )  # This will look for the URL pattern named "project-list" which is automatically generated by the router for the ProjectViewSet  # noqa: E501

    def test_get_projects(self):
        """Test retrieving projects list using /api/project/."""
        url = self.project_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Project")
        self.assertEqual(response.data[0]["uri"], "http://test.com/project")

    def test_get_project_by_id(self):
        """Test retrieving a specific project by id /api/project/{id}/."""
        url = self.project_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.project_id)
        self.assertEqual(response.data["name"], "Test Project")
        self.assertEqual(response.data["uri"], "http://test.com/project")

    def test_update_project(self):
        """Test the PUT /project/{id}/ endpoint."""
        data = {
            "name": "Updated Test Project",
        }
        response = self.client.put(self.project_detail, data, format="json")
        self.project.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.project.name)

    def test_project_readonly_fields(self):
        """Test that read-only fields of Project cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.project_detail, data, format="json")
        self.project.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.project_id)
        self.assertEqual(response.data["id"], str(self.project_id))  # The ID should remain unchanged
        self.assertEqual(data["name"], self.project.name)

    def test_post_project(self):
        """Test the POST api/project/ endpoint."""
        data = {"name": "New Test Project", "uri": "http://test.com/project"}
        response = self.client.post(self.project_list, data, format="json")
        project_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Project.objects.count(), 2)
        project_instance = Project.objects.get(id=project_id)
        self.assertEqual(project_instance.name, "New Test Project")

    def test_delete_project(self):
        """Test the DELETE /api/project/{id}/ endpoint."""
        response = self.client.delete(self.project_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Project.objects.count(), 0)


class SensorTests(APITestCase):
    """Tests for the Sensor model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.sensor = Sensor.objects.create(name="Test Sensor", uri="http://test.com/sensor")
        cls.sensor.save()
        cls.sensor_id = cls.sensor.id
        cls.sensor_detail = reverse(
            "sensor-detail", kwargs={"pk": cls.sensor_id}
        )  # This will look for the URL pattern named "sensor-detail" which is automatically generated by the router for the SensorViewSet and pass the sensor  # noqa: E501
        cls.sensor_list = reverse(
            "sensor-list"
        )  # This will look for the URL pattern named "sensor-list" which is automatically generated by the router for the SensorViewSet  # noqa: E501

    def test_get_sensors(self):
        """Test retrieving sensors list using /api/sensor/."""
        url = self.sensor_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["name"], "Test Sensor")
        self.assertEqual(response.data[0]["uri"], "http://test.com/sensor")

    def test_get_sensor_by_id(self):
        """Test retrieving a specific sensor by id /api/sensor/{id}/."""
        url = self.sensor_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.sensor_id)
        self.assertEqual(response.data["name"], "Test Sensor")
        self.assertEqual(response.data["uri"], "http://test.com/sensor")

    def test_update_sensor(self):
        """Test the PUT /sensor/{id}/ endpoint."""
        data = {
            "name": "Updated Test Sensor",
        }
        response = self.client.put(self.sensor_detail, data, format="json")
        self.sensor.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["name"], self.sensor.name)

    def test_sensor_readonly_fields(self):
        """Test that read-only fields of Sensor cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "name": "Attempted Update",
        }
        response = self.client.put(self.sensor_detail, data, format="json")
        self.sensor.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.sensor_id)
        self.assertEqual(response.data["id"], str(self.sensor_id))  # The ID should remain unchanged
        self.assertEqual(data["name"], self.sensor.name)

    def test_post_sensor(self):
        """Test the POST api/sensor/ endpoint."""
        data = {"name": "New Test Sensor", "uri": "http://test.com/sensor"}
        response = self.client.post(self.sensor_list, data, format="json")
        sensor_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Sensor.objects.count(), 2)
        sensor_instance = Sensor.objects.get(id=sensor_id)
        self.assertEqual(sensor_instance.name, "New Test Sensor")

    def test_delete_sensor(self):
        """Test the DELETE /api/sensor/{id}/ endpoint."""
        response = self.client.delete(self.sensor_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Sensor.objects.count(), 0)


class RelatedMaterialTests(APITestCase):
    """Tests for the RelatedMaterial model."""

    @classmethod
    def setUpTestData(cls):
        """Set up test data."""
        cls.related_material = RelatedMaterial.objects.create(
            uri="http://test.com/relatedmaterial", title="Test RelatedMaterial", relation="Test Relation"
        )
        cls.related_material.save()
        cls.related_material_id = cls.related_material.id
        cls.related_material_detail = reverse(
            "relatedmaterial-detail", kwargs={"pk": cls.related_material_id}
        )  # This will look for the URL pattern named "relatedmaterial-detail" which is automatically generated by the router for the RelatedMaterialViewSet and pass the related_material  # noqa: E501
        cls.related_material_list = reverse(
            "relatedmaterial-list"
        )  # This will look for the URL pattern named "relatedmaterial-list" which is automatically generated by the router for the RelatedMaterialViewSet  # noqa: E501

    def test_get_related_materials(self):
        """Test retrieving related_materials list using /api/relatedmaterial/."""
        url = self.related_material_list
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["title"], "Test RelatedMaterial")
        self.assertEqual(response.data[0]["uri"], "http://test.com/relatedmaterial")
        self.assertEqual(response.data[0]["relation"], "Test Relation")

    def test_get_related_material_by_id(self):
        """Test retrieving a specific related_material by id /api/relatedmaterial/{id}/."""
        url = self.related_material_detail
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(UUID(response.data["id"]), self.related_material_id)
        self.assertEqual(response.data["title"], "Test RelatedMaterial")
        self.assertEqual(response.data["uri"], "http://test.com/relatedmaterial")
        self.assertEqual(response.data["relation"], "Test Relation")

    def test_update_related_material(self):
        """Test the PUT /relatedmaterial/{id}/ endpoint."""
        data = {
            "title": "Updated Test RelatedMaterial",
            "uri": "http://test.com/updated-related-material"
        }
        response = self.client.put(self.related_material_detail, data, format="json")
        self.related_material.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(data["title"], self.related_material.title)
        self.assertEqual(data["uri"], self.related_material.uri)

    def test_related_material_readonly_fields(self):
        """Test that read-only fields of RelatedMaterial cannot be updated."""
        data = {
            "id": "12345678-1234-5678-1234-567812345678",  # Attempt to change the ID
            "uri": "http://test.com/updated-related-material"
        }
        response = self.client.put(self.related_material_detail, data, format="json")
        self.related_material.refresh_from_db()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertNotEqual(UUID(data["id"]), self.related_material_id)
        self.assertEqual(response.data["id"], str(self.related_material_id))  # The ID should remain unchanged
        self.assertEqual(data["uri"], self.related_material.uri)

    def test_post_related_material(self):
        """Test the POST api/relatedmaterial/ endpoint."""
        data = {"title": "New Test RelatedMaterial", "uri": "http://test.com/relatedmaterial"}
        response = self.client.post(self.related_material_list, data, format="json")
        related_material_id = UUID(response.data.get("id"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(RelatedMaterial.objects.count(), 2)
        related_material_instance = RelatedMaterial.objects.get(id=related_material_id)
        self.assertEqual(related_material_instance.uri, "http://test.com/relatedmaterial")

    def test_delete_related_material(self):
        """Test the DELETE /api/relatedmaterial/{id}/ endpoint."""
        response = self.client.delete(self.related_material_detail)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(RelatedMaterial.objects.count(), 0)
