apiVersion: v1
kind: Service
metadata:
  name: {{ include "paidiver-annotations-api.fullname" . }}
  labels:
    {{- include "paidiver-annotations-api.labels" . | nindent 4 }}
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort