apiVersion: v1
kind: Service
metadata:
  name: {{ include "paidiver-annotations-api.fullname" . }}
  labels:
    {{- include "paidiver-annotations-api.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ .Values.api.component_name }}
  ports:
    - port: 8000
      targetPort: {{ .Values.api.port }}