# Generated by Django 4.2.3 on 2026-02-04 18:24

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotation_platform', models.CharField(blank=True, help_text="The platform used to create the annotation, e.g., 'BIIGLE', 'VARS', 'SQUIDLE+', none", max_length=255, null=True)),
                ('shape', models.CharField(choices=[('single-pixel', 'single_pixel'), ('polyline', 'polyline'), ('polygon', 'polygon'), ('circle', 'circle'), ('rectangle', 'rectangle'), ('ellipse', 'ellipse'), ('whole-image', 'whole_image')], help_text='The annotation shape is specified by a keyword.', max_length=32)),
                ('coordinates', models.JSONField(help_text='The pixel coordinates of one annotation. The top-left corner of an image is the (0,0) coordinate. The x-axis is the horizontal axis. Pixel coordinates may be fractional. Coordinates are to be given as a list of lists (only one element for photos, optionally multiple elements for videos). The required number of pixel coordinates is defined by the shape (0 for whole-image, 2 for single-pixel, 3 for circle, 8 for ellipse/rectangle, 4 or more for polyline, 8 or more for polygon). The third coordinate value of a circle defines the radius. The first and last coordinates of a polygon must be equal. Format: [[p1.x,p1.y,p2x,p2.y,...]..]')),
                ('dimension_pixels', models.FloatField(blank=True, help_text='The real-world dimension (e.g., length, diameter) in pixels corresponding to the annotation, if applicable', null=True)),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
        migrations.CreateModel(
            name='AnnotationSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A unique name for the image set, image or annotation set.', max_length=255, unique=True)),
                ('handle', models.CharField(blank=True, help_text='A Handle URL to point to the landing page of the image set, image or annotation set.', max_length=2048, null=True)),
                ('copyright', models.CharField(blank=True, help_text='Copyright statement or contact person or office for the image set, image or annotation set.', max_length=500, null=True)),
                ('abstract', models.TextField(blank=True, help_text='500 - 2000 characters describing what, when, where, why and how the data was collected/annotated. Includes general information on the event (aka station, experiment), e.g. overlap between images/frames, parameters on platform movement, aims, purpose of image capture etc.', null=True)),
                ('objective', models.TextField(blank=True, help_text='A general description of the aims and objectives...', null=True)),
                ('target_environment', models.TextField(blank=True, help_text='A description of the habitat or environment...', null=True)),
                ('target_timescale', models.TextField(blank=True, help_text='A description of the period or temporal environment...', null=True)),
                ('curation_protocol', models.TextField(blank=True, help_text='A description of the image/annotation and metadata curation...', null=True)),
                ('version', models.CharField(blank=True, help_text='The version of the annotation set.', max_length=50, null=True)),
            ],
            options={
                'db_table': 'annotation_sets',
            },
        ),
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A human-readable name for the annotator (identifying the specific human or machine)', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'annotators',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'contexts',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'creators',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A unique name for the image set, image or annotation set.', max_length=255, unique=True)),
                ('handle', models.CharField(blank=True, help_text='A Handle URL to point to the landing page of the image set, image or annotation set.', max_length=2048, null=True)),
                ('copyright', models.CharField(blank=True, help_text='Copyright statement or contact person or office for the image set, image or annotation set.', max_length=500, null=True)),
                ('abstract', models.TextField(blank=True, help_text='500 - 2000 characters describing what, when, where, why and how the data was collected/annotated. Includes general information on the event (aka station, experiment), e.g. overlap between images/frames, parameters on platform movement, aims, purpose of image capture etc.', null=True)),
                ('objective', models.TextField(blank=True, help_text='A general description of the aims and objectives...', null=True)),
                ('target_environment', models.TextField(blank=True, help_text='A description of the habitat or environment...', null=True)),
                ('target_timescale', models.TextField(blank=True, help_text='A description of the period or temporal environment...', null=True)),
                ('curation_protocol', models.TextField(blank=True, help_text='A description of the image/annotation and metadata curation...', null=True)),
                ('sha256_hash', models.CharField(blank=True, help_text='An SHA256 hash to represent the whole file for integrity verification', max_length=64, null=True, unique=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='UTC time of image acquisition (or start time of a video)', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic location of the center of the image set, in WGS84 coordinates (EPSG:4326)', null=True, srid=4326)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True)),
                ('altitude_meters', models.FloatField(blank=True, help_text='Z-coordinate of camera center in meters. Positive above sea level, negative below.', null=True)),
                ('coordinate_uncertainty_meters', models.FloatField(blank=True, help_text='The average/static uncertainty of coordinates in this image set, in meters.', null=True)),
                ('entropy', models.FloatField(blank=True, help_text='Information content of an image / frame according to Shannon entropy.', null=True)),
                ('particle_count', models.IntegerField(blank=True, help_text='Counts of single particles/objects in an image / frame', null=True)),
                ('average_color', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='The average colour for each image / frame and the n channels of an image (e.g. 3 for RGB). The values are in the range 0-255.', null=True, size=None)),
                ('mpeg7_color_layout', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_color_statistic', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_color_structure', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_dominant_color', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_edge_histogram', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_homogeneous_texture', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_scalable_color', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('acquisition', models.CharField(blank=True, choices=[('photo', 'photo'), ('video', 'video'), ('slide', 'slide')], max_length=50, null=True)),
                ('quality', models.CharField(blank=True, choices=[('raw', 'raw'), ('processed', 'processed'), ('product', 'product')], max_length=50, null=True)),
                ('deployment', models.CharField(blank=True, choices=[('mapping', 'mapping'), ('stationary', 'stationary'), ('survey', 'survey'), ('exploration', 'exploration'), ('experiment', 'experiment'), ('sampling', 'sampling')], max_length=50, null=True)),
                ('navigation', models.CharField(blank=True, choices=[('satellite', 'satellite'), ('beacon', 'beacon'), ('transponder', 'transponder'), ('reconstructed', 'reconstructed')], max_length=50, null=True)),
                ('scale_reference', models.CharField(blank=True, choices=[('3D camera', 'camera_3d'), ('calibrated camera', 'camera_calibrated'), ('laser marker', 'laser_marker'), ('optical flow', 'optical_flow')], max_length=50, null=True)),
                ('illumination', models.CharField(blank=True, choices=[('sunlight', 'sunlight'), ('artificial light', 'artificial_light'), ('mixed light', 'mixed_light')], max_length=50, null=True)),
                ('pixel_magnitude', models.CharField(blank=True, choices=[('km', 'km'), ('hm', 'hm'), ('dam', 'dam'), ('m', 'm'), ('cm', 'cm'), ('mm', 'mm'), ('µm', 'um')], max_length=50, null=True)),
                ('marine_zone', models.CharField(blank=True, choices=[('seafloor', 'seafloor'), ('water column', 'water_column'), ('sea surface', 'sea_surface'), ('atmosphere', 'atmosphere'), ('laboratory', 'laboratory')], max_length=50, null=True)),
                ('spectral_resolution', models.CharField(blank=True, choices=[('grayscale', 'grayscale'), ('rgb', 'rgb'), ('multi-spectral', 'multi_spectral'), ('hyper-spectral', 'hyper_spectral')], max_length=50, null=True)),
                ('capture_mode', models.CharField(blank=True, choices=[('timer', 'timer'), ('manual', 'manual'), ('mixed', 'mixed')], max_length=50, null=True)),
                ('fauna_attraction', models.CharField(blank=True, choices=[('none', 'none'), ('baited', 'baited'), ('light', 'light')], max_length=50, null=True)),
                ('area_square_meters', models.FloatField(blank=True, null=True)),
                ('meters_above_ground', models.FloatField(blank=True, null=True)),
                ('acquisition_settings', models.JSONField(blank=True, null=True)),
                ('camera_yaw_degrees', models.FloatField(blank=True, null=True)),
                ('camera_pitch_degrees', models.FloatField(blank=True, null=True)),
                ('camera_roll_degrees', models.FloatField(blank=True, null=True)),
                ('overlap_fraction', models.FloatField(blank=True, null=True)),
                ('spatial_constraints', models.TextField(blank=True, null=True)),
                ('temporal_constraints', models.TextField(blank=True, null=True)),
                ('time_synchronisation', models.TextField(blank=True, null=True)),
                ('item_identification_scheme', models.TextField(blank=True, null=True)),
                ('visual_constraints', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ImageCameraCalibrationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibration_model_type', models.CharField(blank=True, help_text='e.g.: rectilinear air, rectilinear water, fisheye air, fisheye water, other', max_length=100, null=True)),
                ('focal_length_xy_pixel', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='2D focal length in pixels', null=True, size=None)),
                ('principal_point_xy_pixel', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='2D principal point in pixels (top left pixel center is 0,0, x right, y down)', null=True, size=None)),
                ('distortion_coefficients', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='rectilinear: k1,k2,p1,p2,k3,k4,k5,k6; fisheye: k1,k2,k3,k4', null=True, size=None)),
                ('approximate_field_of_view_water_xy_degree', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Proxy for pixel to meter conversion, and as backup', null=True, size=None)),
                ('extra_description', models.TextField(blank=True, help_text='Explain model, or if lens parameters are in mm rather than in pixel', null=True)),
            ],
            options={
                'db_table': 'image_camera_calibration_models',
            },
        ),
        migrations.CreateModel(
            name='ImageCameraHousingViewport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewport_type', models.CharField(blank=True, help_text='e.g.: flat port, dome port, other', max_length=100, null=True)),
                ('optical_density', models.FloatField(blank=True, help_text='Unit-less optical density (1.0=vacuum)', null=True)),
                ('thickness_millimeters', models.FloatField(blank=True, help_text='Thickness of viewport in millimeters', null=True)),
                ('extra_description', models.TextField(blank=True, help_text='A textual description of the viewport used', null=True)),
            ],
            options={
                'db_table': 'image_camera_housing_viewports',
            },
        ),
        migrations.CreateModel(
            name='ImageCameraPose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utm_zone', models.CharField(blank=True, help_text='The UTM zone number', max_length=10, null=True)),
                ('utm_epsg', models.CharField(blank=True, help_text='The EPSG code of the UTM zone', max_length=10, null=True)),
                ('utm_east_north_up_meters', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='The position of the camera center in UTM coordinates.', null=True, size=None)),
                ('absolute_orientation_utm_matrix', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='3x3 row-major float rotation matrix that transforms a direction in camera coordinates (x,y,z = right,down,line of sight) into a direction in UTM coordinates (x,y,z = easting,northing,up)', null=True, size=None)),
            ],
            options={
                'db_table': 'image_camera_poses',
            },
        ),
        migrations.CreateModel(
            name='ImageDomeportParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outer_radius_millimeters', models.FloatField(blank=True, help_text='Outer radius of the dome port - the part that has contact with the water.', null=True)),
                ('decentering_offset_xyz_millimeters', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='3D offset vector of the camera center from the dome port center in millimeters', null=True, size=None)),
                ('extra_description', models.TextField(blank=True, help_text='A textual description of the dome port used', null=True)),
            ],
            options={
                'db_table': 'image_domeport_parameters',
            },
        ),
        migrations.CreateModel(
            name='ImageFlatportParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens_port_distance_millimeters', models.FloatField(blank=True, help_text='Distance between the front of the camera lens and the inner side of the housing viewport in millimeters.', null=True)),
                ('interface_normal_direction', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='3D direction vector to specify how the view direction of the lens intersects with the viewport (unit-less, (0,0,1) is aligned)', null=True, size=None)),
                ('extra_description', models.TextField(blank=True, help_text='A textual description of the flat port used', null=True)),
            ],
            options={
                'db_table': 'image_flatport_parameters',
            },
        ),
        migrations.CreateModel(
            name='ImagePhotometricCalibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_white_balancing', models.TextField(blank=True, help_text='How white-balancing was done.', null=True)),
                ('exposure_factor_rgb', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='RGB factors applied to this image (product of ISO, exposure time, relative white balance)', null=True, size=None)),
                ('sequence_illumination_type', models.CharField(blank=True, help_text='e.g. constant artificial, globally adapted artificial, individually varying light sources, sunlight, mixed', max_length=100, null=True)),
                ('sequence_illumination_description', models.TextField(blank=True, help_text='How the image sequence was illuminated', null=True)),
                ('illumination_factor_rgb', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='RGB factors applied to artificial lights for this image', null=True, size=None)),
                ('water_properties_description', models.TextField(blank=True, help_text='Photometric properties of the water within which the images were captured', null=True)),
            ],
            options={
                'db_table': 'image_photometric_calibrations',
            },
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A unique name for the image set, image or annotation set.', max_length=255, unique=True)),
                ('handle', models.CharField(blank=True, help_text='A Handle URL to point to the landing page of the image set, image or annotation set.', max_length=2048, null=True)),
                ('copyright', models.CharField(blank=True, help_text='Copyright statement or contact person or office for the image set, image or annotation set.', max_length=500, null=True)),
                ('abstract', models.TextField(blank=True, help_text='500 - 2000 characters describing what, when, where, why and how the data was collected/annotated. Includes general information on the event (aka station, experiment), e.g. overlap between images/frames, parameters on platform movement, aims, purpose of image capture etc.', null=True)),
                ('objective', models.TextField(blank=True, help_text='A general description of the aims and objectives...', null=True)),
                ('target_environment', models.TextField(blank=True, help_text='A description of the habitat or environment...', null=True)),
                ('target_timescale', models.TextField(blank=True, help_text='A description of the period or temporal environment...', null=True)),
                ('curation_protocol', models.TextField(blank=True, help_text='A description of the image/annotation and metadata curation...', null=True)),
                ('sha256_hash', models.CharField(blank=True, help_text='An SHA256 hash to represent the whole file for integrity verification', max_length=64, null=True, unique=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='UTC time of image acquisition (or start time of a video)', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic location of the center of the image set, in WGS84 coordinates (EPSG:4326)', null=True, srid=4326)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True)),
                ('altitude_meters', models.FloatField(blank=True, help_text='Z-coordinate of camera center in meters. Positive above sea level, negative below.', null=True)),
                ('coordinate_uncertainty_meters', models.FloatField(blank=True, help_text='The average/static uncertainty of coordinates in this image set, in meters.', null=True)),
                ('entropy', models.FloatField(blank=True, help_text='Information content of an image / frame according to Shannon entropy.', null=True)),
                ('particle_count', models.IntegerField(blank=True, help_text='Counts of single particles/objects in an image / frame', null=True)),
                ('average_color', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='The average colour for each image / frame and the n channels of an image (e.g. 3 for RGB). The values are in the range 0-255.', null=True, size=None)),
                ('mpeg7_color_layout', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_color_statistic', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_color_structure', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_dominant_color', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_edge_histogram', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_homogeneous_texture', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('mpeg7_scalable_color', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='An nD feature vector per image / frame...', null=True, size=None)),
                ('acquisition', models.CharField(blank=True, choices=[('photo', 'photo'), ('video', 'video'), ('slide', 'slide')], max_length=50, null=True)),
                ('quality', models.CharField(blank=True, choices=[('raw', 'raw'), ('processed', 'processed'), ('product', 'product')], max_length=50, null=True)),
                ('deployment', models.CharField(blank=True, choices=[('mapping', 'mapping'), ('stationary', 'stationary'), ('survey', 'survey'), ('exploration', 'exploration'), ('experiment', 'experiment'), ('sampling', 'sampling')], max_length=50, null=True)),
                ('navigation', models.CharField(blank=True, choices=[('satellite', 'satellite'), ('beacon', 'beacon'), ('transponder', 'transponder'), ('reconstructed', 'reconstructed')], max_length=50, null=True)),
                ('scale_reference', models.CharField(blank=True, choices=[('3D camera', 'camera_3d'), ('calibrated camera', 'camera_calibrated'), ('laser marker', 'laser_marker'), ('optical flow', 'optical_flow')], max_length=50, null=True)),
                ('illumination', models.CharField(blank=True, choices=[('sunlight', 'sunlight'), ('artificial light', 'artificial_light'), ('mixed light', 'mixed_light')], max_length=50, null=True)),
                ('pixel_magnitude', models.CharField(blank=True, choices=[('km', 'km'), ('hm', 'hm'), ('dam', 'dam'), ('m', 'm'), ('cm', 'cm'), ('mm', 'mm'), ('µm', 'um')], max_length=50, null=True)),
                ('marine_zone', models.CharField(blank=True, choices=[('seafloor', 'seafloor'), ('water column', 'water_column'), ('sea surface', 'sea_surface'), ('atmosphere', 'atmosphere'), ('laboratory', 'laboratory')], max_length=50, null=True)),
                ('spectral_resolution', models.CharField(blank=True, choices=[('grayscale', 'grayscale'), ('rgb', 'rgb'), ('multi-spectral', 'multi_spectral'), ('hyper-spectral', 'hyper_spectral')], max_length=50, null=True)),
                ('capture_mode', models.CharField(blank=True, choices=[('timer', 'timer'), ('manual', 'manual'), ('mixed', 'mixed')], max_length=50, null=True)),
                ('fauna_attraction', models.CharField(blank=True, choices=[('none', 'none'), ('baited', 'baited'), ('light', 'light')], max_length=50, null=True)),
                ('area_square_meters', models.FloatField(blank=True, null=True)),
                ('meters_above_ground', models.FloatField(blank=True, null=True)),
                ('acquisition_settings', models.JSONField(blank=True, null=True)),
                ('camera_yaw_degrees', models.FloatField(blank=True, null=True)),
                ('camera_pitch_degrees', models.FloatField(blank=True, null=True)),
                ('camera_roll_degrees', models.FloatField(blank=True, null=True)),
                ('overlap_fraction', models.FloatField(blank=True, null=True)),
                ('spatial_constraints', models.TextField(blank=True, null=True)),
                ('temporal_constraints', models.TextField(blank=True, null=True)),
                ('time_synchronisation', models.TextField(blank=True, null=True)),
                ('item_identification_scheme', models.TextField(blank=True, null=True)),
                ('visual_constraints', models.TextField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, default='../raw', help_text='Local relative or absolute path to a directory in which (also its sub-directories), the referenced image files are located. Absolute paths must start with and relative paths without path separator (ignoring drive letters on windows). The default is the relative path `../raw`.', max_length=500, null=True)),
                ('min_latitude_degrees', models.FloatField(blank=True, help_text='The lower bounding box latitude...', null=True)),
                ('max_latitude_degrees', models.FloatField(blank=True, help_text='The upper bounding box latitude...', null=True)),
                ('min_longitude_degrees', models.FloatField(blank=True, help_text='The lower bounding box longitude...', null=True)),
                ('max_longitude_degrees', models.FloatField(blank=True, help_text='The upper bounding box longitude...', null=True)),
                ('limits', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geographic bounding box of the image_set in WGS84 coordinates.', null=True, srid=4326)),
                ('camera_calibration_model', models.ForeignKey(blank=True, db_column='camera_calibration_model_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='api.imagecameracalibrationmodel')),
                ('camera_housing_viewport', models.ForeignKey(blank=True, db_column='camera_housing_viewport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='api.imagecamerahousingviewport')),
                ('camera_pose', models.ForeignKey(blank=True, db_column='camera_pose_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='api.imagecamerapose')),
                ('context', models.ForeignKey(blank=True, db_column='context_id', help_text='The overarching project context within which the image set was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.context')),
            ],
            options={
                'db_table': 'image_sets',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'pis',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='RelatedMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(help_text='The URI pointing to a related resource', max_length=255)),
                ('title', models.CharField(blank=True, help_text='A name characterising the resource that is pointed to', max_length=255, null=True)),
                ('relation', models.TextField(blank=True, help_text='A textual explanation how this material is related to this image set', null=True)),
            ],
            options={
                'db_table': 'related_materials',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name in BIIGLE label tree output; name of label as annotated', max_length=255, unique=True)),
                ('parent_label_name', models.CharField(help_text='Name of parent to label_name', max_length=255)),
                ('lowest_taxonomic_name', models.CharField(blank=True, help_text='Most detailed taxonomic identification possible; scientificName field in DarwinCore', max_length=255, null=True)),
                ('lowest_aphia_id', models.CharField(blank=True, help_text='The AphiaID corresponding to the lowest_taxonomic_name, if applicable', max_length=50, null=True)),
                ('name_is_lowest', models.BooleanField(default=False, help_text='Indicates whether the name field represents the lowest taxonomic identification')),
                ('identification_qualifier', models.CharField(blank=True, help_text='Open nomenclature signs (see Horton et al 2021); same field name in DarwinCore', max_length=255, null=True)),
                ('annotation_set', models.ForeignKey(help_text='The annotation_set this label belongs to. An annotation_set can have multiple labels.', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.annotationset')),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='ImageSetRelatedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_set', models.ForeignKey(db_column='image_set_id', on_delete=django.db.models.deletion.CASCADE, to='api.imageset')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='api.relatedmaterial')),
            ],
            options={
                'db_table': 'image_set_related_materials',
            },
        ),
        migrations.CreateModel(
            name='ImageSetCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to='api.creator')),
                ('image_set', models.ForeignKey(db_column='image_set_id', on_delete=django.db.models.deletion.CASCADE, to='api.imageset')),
            ],
            options={
                'db_table': 'image_set_creators',
            },
        ),
        migrations.AddField(
            model_name='imageset',
            name='creators',
            field=models.ManyToManyField(help_text='Information to identify the creators of the image set', related_name='image_sets', through='api.ImageSetCreator', to='api.creator'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='domeport_parameter',
            field=models.ForeignKey(blank=True, db_column='domeport_parameter_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='api.imagedomeportparameter'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', help_text='One event of a project or expedition or cruise or experiment or ... that led to the creation of this image set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.event'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='flatport_parameter',
            field=models.ForeignKey(blank=True, db_column='flatport_parameter_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='api.imageflatportparameter'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='license',
            field=models.ForeignKey(blank=True, db_column='license_id', help_text='A URI pointing to the license to use the data (should be FAIR, e.g. CC-BY or CC-0)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.license'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='photometric_calibration',
            field=models.ForeignKey(blank=True, db_column='photometric_calibration_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='api.imagephotometriccalibration'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='pi',
            field=models.ForeignKey(blank=True, db_column='pi_id', help_text='A URI pointing to a description of the principal investigator of the image set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.pi'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='platform',
            field=models.ForeignKey(blank=True, db_column='platform_id', help_text='A URI pointing to a description of the camera platform used to create this image set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.platform'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', help_text='The more specific project or expedition or cruise or experiment or ... within which the image set was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.project'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='related_materials',
            field=models.ManyToManyField(related_name='image_sets', through='api.ImageSetRelatedMaterial', to='api.relatedmaterial'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='sensor',
            field=models.ForeignKey(blank=True, db_column='sensor_id', help_text='A URI pointing to a description of the sensor used to create this image set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='api.sensor'),
        ),
        migrations.CreateModel(
            name='ImageCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to='api.creator')),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'db_table': 'image_creators',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='camera_calibration_model',
            field=models.ForeignKey(blank=True, db_column='camera_calibration_model_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imagecameracalibrationmodel'),
        ),
        migrations.AddField(
            model_name='image',
            name='camera_housing_viewport',
            field=models.ForeignKey(blank=True, db_column='camera_housing_viewport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imagecamerahousingviewport'),
        ),
        migrations.AddField(
            model_name='image',
            name='camera_pose',
            field=models.ForeignKey(blank=True, db_column='camera_pose_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imagecamerapose'),
        ),
        migrations.AddField(
            model_name='image',
            name='context',
            field=models.ForeignKey(blank=True, db_column='context_id', help_text='The overarching project context within which the image set was created', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.context'),
        ),
        migrations.AddField(
            model_name='image',
            name='creators',
            field=models.ManyToManyField(help_text='Information to identify the creators of the image set', related_name='images', through='api.ImageCreator', to='api.creator'),
        ),
        migrations.AddField(
            model_name='image',
            name='domeport_parameter',
            field=models.ForeignKey(blank=True, db_column='domeport_parameter_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imagedomeportparameter'),
        ),
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', help_text='One event of a project or expedition or cruise or experiment or ... that led to the creation of this image set.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event'),
        ),
        migrations.AddField(
            model_name='image',
            name='flatport_parameter',
            field=models.ForeignKey(blank=True, db_column='flatport_parameter_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imageflatportparameter'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_set',
            field=models.ForeignKey(db_column='image_set_id', help_text='The image_set this image belongs to. A image_set can have multiple images.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.imageset'),
        ),
        migrations.AddField(
            model_name='image',
            name='license',
            field=models.ForeignKey(blank=True, db_column='license_id', help_text='A URI pointing to the license to use the data (should be FAIR, e.g. CC-BY or CC-0)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.license'),
        ),
        migrations.AddField(
            model_name='image',
            name='photometric_calibration',
            field=models.ForeignKey(blank=True, db_column='photometric_calibration_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imagephotometriccalibration'),
        ),
        migrations.AddField(
            model_name='image',
            name='pi',
            field=models.ForeignKey(blank=True, db_column='pi_id', help_text='A URI pointing to a description of the principal investigator of the image set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pi'),
        ),
        migrations.AddField(
            model_name='image',
            name='platform',
            field=models.ForeignKey(blank=True, db_column='platform_id', help_text='A URI pointing to a description of the camera platform used to create this image set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.platform'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', help_text='The more specific project or expedition or cruise or experiment or ... within which the image set was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.AddField(
            model_name='image',
            name='sensor',
            field=models.ForeignKey(blank=True, db_column='sensor_id', help_text='A URI pointing to a description of the sensor used to create this image set.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sensor'),
        ),
        migrations.CreateModel(
            name='AnnotationSetImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_set', models.ForeignKey(db_column='annotation_set_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_set_image_set_links', to='api.annotationset')),
                ('image_set', models.ForeignKey(db_column='image_set_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_set_image_set_links', to='api.imageset')),
            ],
            options={
                'db_table': 'annotation_set_image_sets',
            },
        ),
        migrations.CreateModel(
            name='AnnotationSetCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_set', models.ForeignKey(db_column='annotation_set_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_set_creator_links', to='api.annotationset')),
                ('creator', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_set_creator_links', to='api.creator')),
            ],
            options={
                'db_table': 'annotation_set_creators',
            },
        ),
        migrations.AddField(
            model_name='annotationset',
            name='context',
            field=models.ForeignKey(blank=True, help_text='The overarching project context within which the annotation set was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_sets', to='api.context'),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='creators',
            field=models.ManyToManyField(blank=True, help_text='Information to identify the creators of the annotation set', related_name='annotation_sets', through='api.AnnotationSetCreator', to='api.creator'),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='image_sets',
            field=models.ManyToManyField(blank=True, help_text='Relationship to image_sets included in this annotation set.', related_name='annotation_sets', through='api.AnnotationSetImageSet', to='api.imageset'),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='license',
            field=models.ForeignKey(blank=True, help_text='A URI pointing to the license to use the data (should be FAIR, e.g. CC-BY or CC-0)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_sets', to='api.license'),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='pi',
            field=models.ForeignKey(blank=True, help_text='A URI pointing to a description of the principal investigator of the annotation set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_sets', to='api.pi'),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The more specific project or expedition or cruise or experiment or ... within which the annotation set was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_sets', to='api.project'),
        ),
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_datetime', models.DateTimeField(help_text='The date-time stamp of label creation')),
                ('annotation', models.ForeignKey(help_text='A unique identifier to the annotation this label is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_labels', to='api.annotation')),
                ('annotator', models.ForeignKey(blank=True, help_text='A unique identifier to an annotation creator, e.g. orcid URL or handle to ML model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_labels', to='api.annotator')),
                ('label', models.ForeignKey(help_text='A unique identifier to a semantic label', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_labels', to='api.label')),
            ],
            options={
                'db_table': 'annotation_labels',
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_set',
            field=models.ForeignKey(help_text='The annotation set this annotation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.annotationset'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(help_text='A unique identifier to the image this annotation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.image'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='annotations', through='api.AnnotationLabel', to='api.label'),
        ),
        migrations.AddConstraint(
            model_name='imagesetrelatedmaterial',
            constraint=models.UniqueConstraint(fields=('image_set', 'material'), name='uq_image_set_related_materials'),
        ),
        migrations.AddConstraint(
            model_name='imagesetcreator',
            constraint=models.UniqueConstraint(fields=('image_set', 'creator'), name='uq_image_set_creators'),
        ),
        migrations.AddConstraint(
            model_name='imagecreator',
            constraint=models.UniqueConstraint(fields=('image', 'creator'), name='uq_image_creators'),
        ),
        migrations.AddConstraint(
            model_name='annotationsetimageset',
            constraint=models.UniqueConstraint(fields=('annotation_set', 'image_set'), name='uq_annotation_set_image_set'),
        ),
        migrations.AddConstraint(
            model_name='annotationsetcreator',
            constraint=models.UniqueConstraint(fields=('annotation_set', 'creator'), name='uq_annotation_set_creator'),
        ),
        migrations.AddConstraint(
            model_name='annotationlabel',
            constraint=models.UniqueConstraint(fields=('label', 'annotation', 'annotator'), name='uq_annotation_label_annotation_annotator'),
        ),
    ]
