# Generated by Django 4.2.3 on 2026-02-06 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the camera center in degrees, WGS84 coordinates (EPSG:4326)', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='max_latitude_degrees',
            field=models.FloatField(blank=True, help_text='The upper bounding box latitude...', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='max_longitude_degrees',
            field=models.FloatField(blank=True, help_text='The upper bounding box longitude...', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='min_latitude_degrees',
            field=models.FloatField(blank=True, help_text='The lower bounding box latitude...', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='min_longitude_degrees',
            field=models.FloatField(blank=True, help_text='The lower bounding box longitude...', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddConstraint(
            model_name='imageset',
            constraint=models.CheckConstraint(check=models.Q(('min_latitude_degrees__isnull', True), ('max_latitude_degrees__isnull', True), ('min_latitude_degrees__lt', models.F('max_latitude_degrees')), _connector='OR'), name='imageset_min_lat_lt_max_lat'),
        ),
        migrations.AddConstraint(
            model_name='imageset',
            constraint=models.CheckConstraint(check=models.Q(('min_longitude_degrees__isnull', True), ('max_longitude_degrees__isnull', True), ('min_longitude_degrees__lt', models.F('max_longitude_degrees')), _connector='OR'), name='imageset_min_lon_lt_max_lon'),
        ),
    ]
