# Generated by Django 4.2.3 on 2026-02-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_latitude_alter_image_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='filename', help_text='A unique name for the image filename.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotationset',
            name='name',
            field=models.CharField(help_text='A unique name for the annotation set.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='name',
            field=models.CharField(help_text='A unique name for the image set.', max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('filename', 'image_set'), name='uq_image_filename_image_set'),
        ),
    ]
