# Generated by Django 4.2.3 on 2026-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_material_in_imagesetrelatedmaterial_table_to_related_material'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'parent_label_name'), name='unique_label_name_per_parent'),
        ),
    ]
