# Generated by Django 4.2.3 on 2026-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_material_in_imagesetrelatedmaterial_table_to_related_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='lowest_aphia_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='The AphiaID corresponding to the lowest_taxonomic_name, if applicable'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['lowest_aphia_id'], name='labels_lowest_aphia_idx'),
        ),
    ]
