# Generated by Django 4.2.3 on 2026-03-24 12:25

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='lowest_aphia_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The AphiaID corresponding to the lowest_taxonomic_name, if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(db_index=True, help_text='Name in BIIGLE label tree output; name of label as annotated', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['lowest_aphia_id'], name='labels_lowest_aphia_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['name'], name='labels_name_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='labels_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
