# Generated by Django 4.2.3 on 2026-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_label_lowest_aphia_id_alter_label_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(db_index=True, help_text='Name in BIIGLE label tree output; name of label as annotated', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'parent_label_name', 'annotation_set'), name='unique_label_name_per_parent'),
        ),
    ]
