# Generated by Django 4.2.3 on 2026-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_label_lowest_aphia_id_alter_label_name_and_more.py'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'parent_label_name'), name='unique_label_name_per_parent'),
        ),
    ]
