# Generated by Django 4.2.3 on 2026-03-26 13:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_label_lowest_aphia_id_alter_label_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='label',
            name='labels_lowest_aphia_idx',
        ),
        migrations.RemoveIndex(
            model_name='label',
            name='labels_name_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['latitude'], name='images_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['longitude'], name='images_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['deployment'], name='images_deployment_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['fauna_attraction'], name='images_fauna_attraction_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['marine_zone'], name='images_marine_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['latitude'], name='image_set_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['longitude'], name='image_set_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['deployment'], name='image_set_deployment_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['fauna_attraction'], name='image_set_fauna_attraction_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['marine_zone'], name='image_set_marine_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='image_set_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='platform_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='project_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
