# Generated by Django 4.2.3 on 2026-03-27 09:35

import api.models.base
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_label_lowest_aphia_id_alter_label_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='label',
            name='labels_lowest_aphia_idx',
        ),
        migrations.RemoveIndex(
            model_name='label',
            name='labels_name_idx',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='shape',
            field=api.models.base.AliasedShapesEnumField(choices=[('single-pixel', 'single_pixel'), ('polyline', 'polyline'), ('polygon', 'polygon'), ('circle', 'circle'), ('rectangle', 'rectangle'), ('ellipse', 'ellipse'), ('whole-image', 'whole_image')], help_text='The annotation shape is specified by a keyword.', max_length=32),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(db_index=True, help_text='Name in BIIGLE label tree output; name of label as annotated', max_length=255),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['latitude'], name='images_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['longitude'], name='images_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['deployment'], name='images_deployment_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['fauna_attraction'], name='images_fauna_attraction_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['marine_zone'], name='images_marine_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['latitude'], name='image_set_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['longitude'], name='image_set_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['deployment'], name='image_set_deployment_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['fauna_attraction'], name='image_set_fauna_attraction_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=models.Index(fields=['marine_zone'], name='image_set_marine_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='imageset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='image_set_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='platform_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='project_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'parent_label_name', 'annotation_set'), name='unique_label_name_per_parent'),
        ),
    ]
