# Generated by Django 4.2.3 on 2026-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007'
                '_label_composite_unique_key_name_and_parent_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='Name in BIIGLE label tree output; name of label as annotated', max_length=255),
        ),
    ]
