# Generated by Django 4.2.3 on 2026-03-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_label_labels_lowest_aphia_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='creator',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='pi',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pi',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='platform',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='relatedmaterial',
            name='relation',
            field=models.TextField(blank=True, default='', help_text='A textual explanation how this material is related to this image set'),
        ),
        migrations.AlterField(
            model_name='relatedmaterial',
            name='title',
            field=models.CharField(blank=True, default='', help_text='A name characterising the resource that is pointed to', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddConstraint(
            model_name='context',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_context'),
        ),
        migrations.AddConstraint(
            model_name='creator',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_creator'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_event'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_license'),
        ),
        migrations.AddConstraint(
            model_name='pi',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_pi'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_platform'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_project'),
        ),
        migrations.AddConstraint(
            model_name='relatedmaterial',
            constraint=models.UniqueConstraint(fields=('uri', 'title', 'relation'), name='unique_related_material_uri_title_relation'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('name', 'uri'), name='unique_name_uri_api_sensor'),
        ),
    ]
