# Generated by Django 4.2.3 on 2026-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_unique_name_constraint_from_label'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_label_name_per_parent',
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'parent_label_name', 'annotation_set'), name='unique_label_name_per_parent'),
        ),
    ]
