--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg110+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tiger; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tiger;


--
-- Name: tiger_data; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tiger_data;


--
-- Name: topology; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA topology;


--
-- Name: SCHEMA topology; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA topology IS 'PostGIS Topology schema';


--
-- Name: fuzzystrmatch; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA public;


--
-- Name: EXTENSION fuzzystrmatch; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION fuzzystrmatch IS 'determine similarities and distance between strings';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: postgis_tiger_geocoder; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;


--
-- Name: EXTENSION postgis_tiger_geocoder; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis_tiger_geocoder IS 'PostGIS tiger geocoder and reverse geocoder';


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: EXTENSION postgis_topology; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis_topology IS 'PostGIS topology spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: annotation_labels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotation_labels (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    creation_datetime timestamp with time zone NOT NULL,
    annotation_id uuid NOT NULL,
    annotator_id uuid,
    label_id uuid NOT NULL
);


--
-- Name: annotation_set_creators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotation_set_creators (
    id bigint NOT NULL,
    annotation_set_id uuid NOT NULL,
    creator_id uuid NOT NULL
);


--
-- Name: annotation_set_creators_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annotation_set_creators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annotation_set_creators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annotation_set_image_sets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotation_set_image_sets (
    id bigint NOT NULL,
    annotation_set_id uuid NOT NULL,
    image_set_id uuid NOT NULL
);


--
-- Name: annotation_set_image_sets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annotation_set_image_sets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annotation_set_image_sets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annotation_sets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotation_sets (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    handle character varying(2048),
    copyright character varying(500),
    abstract text,
    objective text,
    target_environment text,
    target_timescale text,
    curation_protocol text,
    version character varying(50),
    context_id uuid,
    license_id uuid,
    pi_id uuid,
    project_id uuid
);


--
-- Name: annotations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotations (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    annotation_platform character varying(255),
    shape character varying(32) NOT NULL,
    coordinates jsonb NOT NULL,
    dimension_pixels double precision,
    annotation_set_id uuid NOT NULL,
    image_id uuid NOT NULL
);


--
-- Name: annotators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotators (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: contexts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contexts (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: creators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.creators (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: image_camera_calibration_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_camera_calibration_models (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    calibration_model_type character varying(100),
    focal_length_xy_pixel double precision[],
    principal_point_xy_pixel double precision[],
    distortion_coefficients double precision[],
    approximate_field_of_view_water_xy_degree double precision[],
    extra_description text
);


--
-- Name: image_camera_housing_viewports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_camera_housing_viewports (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    viewport_type character varying(100),
    optical_density double precision,
    thickness_millimeters double precision,
    extra_description text
);


--
-- Name: image_camera_poses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_camera_poses (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    utm_zone character varying(10),
    utm_epsg character varying(10),
    utm_east_north_up_meters double precision[],
    absolute_orientation_utm_matrix double precision[]
);


--
-- Name: image_creators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_creators (
    id bigint NOT NULL,
    creator_id uuid NOT NULL,
    image_id uuid NOT NULL
);


--
-- Name: image_creators_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.image_creators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_creators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: image_domeport_parameters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_domeport_parameters (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    outer_radius_millimeters double precision,
    decentering_offset_xyz_millimeters double precision[],
    extra_description text
);


--
-- Name: image_flatport_parameters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_flatport_parameters (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lens_port_distance_millimeters double precision,
    interface_normal_direction double precision[],
    extra_description text
);


--
-- Name: image_photometric_calibrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_photometric_calibrations (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sequence_white_balancing text,
    exposure_factor_rgb double precision[],
    sequence_illumination_type character varying(100),
    sequence_illumination_description text,
    illumination_factor_rgb double precision[],
    water_properties_description text
);


--
-- Name: image_set_creators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_set_creators (
    id bigint NOT NULL,
    creator_id uuid NOT NULL,
    image_set_id uuid NOT NULL
);


--
-- Name: image_set_creators_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.image_set_creators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_set_creators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: image_set_related_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_set_related_materials (
    id bigint NOT NULL,
    image_set_id uuid NOT NULL,
    related_material_id uuid NOT NULL
);


--
-- Name: image_set_related_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.image_set_related_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_set_related_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: image_sets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_sets (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    handle character varying(2048),
    copyright character varying(500),
    abstract text,
    objective text,
    target_environment text,
    target_timescale text,
    curation_protocol text,
    sha256_hash character varying(64),
    date_time timestamp with time zone,
    geom public.geometry(Point,4326),
    latitude double precision,
    longitude double precision,
    altitude_meters double precision,
    coordinate_uncertainty_meters double precision,
    entropy double precision,
    particle_count integer,
    average_color double precision[],
    mpeg7_color_layout double precision[],
    mpeg7_color_statistic double precision[],
    mpeg7_color_structure double precision[],
    mpeg7_dominant_color double precision[],
    mpeg7_edge_histogram double precision[],
    mpeg7_homogeneous_texture double precision[],
    mpeg7_scalable_color double precision[],
    acquisition character varying(50),
    quality character varying(50),
    deployment character varying(50),
    navigation character varying(50),
    scale_reference character varying(50),
    illumination character varying(50),
    pixel_magnitude character varying(50),
    marine_zone character varying(50),
    spectral_resolution character varying(50),
    capture_mode character varying(50),
    fauna_attraction character varying(50),
    area_square_meters double precision,
    meters_above_ground double precision,
    acquisition_settings jsonb,
    camera_yaw_degrees double precision,
    camera_pitch_degrees double precision,
    camera_roll_degrees double precision,
    overlap_fraction double precision,
    spatial_constraints text,
    temporal_constraints text,
    time_synchronisation text,
    item_identification_scheme text,
    visual_constraints text,
    local_path character varying(500),
    min_latitude_degrees double precision,
    max_latitude_degrees double precision,
    min_longitude_degrees double precision,
    max_longitude_degrees double precision,
    limits public.geometry(Polygon,4326),
    camera_calibration_model_id uuid,
    camera_housing_viewport_id uuid,
    camera_pose_id uuid,
    context_id uuid,
    domeport_parameter_id uuid,
    event_id uuid,
    flatport_parameter_id uuid,
    license_id uuid,
    photometric_calibration_id uuid,
    pi_id uuid,
    platform_id uuid,
    project_id uuid,
    sensor_id uuid,
    CONSTRAINT imageset_min_lat_lt_max_lat CHECK (((min_latitude_degrees IS NULL) OR (max_latitude_degrees IS NULL) OR (min_latitude_degrees < max_latitude_degrees))),
    CONSTRAINT imageset_min_lon_lt_max_lon CHECK (((min_longitude_degrees IS NULL) OR (max_longitude_degrees IS NULL) OR (min_longitude_degrees < max_longitude_degrees)))
);


--
-- Name: images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    handle character varying(2048),
    copyright character varying(500),
    abstract text,
    objective text,
    target_environment text,
    target_timescale text,
    curation_protocol text,
    sha256_hash character varying(64),
    date_time timestamp with time zone,
    geom public.geometry(Point,4326),
    latitude double precision,
    longitude double precision,
    altitude_meters double precision,
    coordinate_uncertainty_meters double precision,
    entropy double precision,
    particle_count integer,
    average_color double precision[],
    mpeg7_color_layout double precision[],
    mpeg7_color_statistic double precision[],
    mpeg7_color_structure double precision[],
    mpeg7_dominant_color double precision[],
    mpeg7_edge_histogram double precision[],
    mpeg7_homogeneous_texture double precision[],
    mpeg7_scalable_color double precision[],
    acquisition character varying(50),
    quality character varying(50),
    deployment character varying(50),
    navigation character varying(50),
    scale_reference character varying(50),
    illumination character varying(50),
    pixel_magnitude character varying(50),
    marine_zone character varying(50),
    spectral_resolution character varying(50),
    capture_mode character varying(50),
    fauna_attraction character varying(50),
    area_square_meters double precision,
    meters_above_ground double precision,
    acquisition_settings jsonb,
    camera_yaw_degrees double precision,
    camera_pitch_degrees double precision,
    camera_roll_degrees double precision,
    overlap_fraction double precision,
    spatial_constraints text,
    temporal_constraints text,
    time_synchronisation text,
    item_identification_scheme text,
    visual_constraints text,
    camera_calibration_model_id uuid,
    camera_housing_viewport_id uuid,
    camera_pose_id uuid,
    context_id uuid,
    domeport_parameter_id uuid,
    event_id uuid,
    flatport_parameter_id uuid,
    image_set_id uuid NOT NULL,
    license_id uuid,
    photometric_calibration_id uuid,
    pi_id uuid,
    platform_id uuid,
    project_id uuid,
    sensor_id uuid,
    filename character varying(255) NOT NULL
);


--
-- Name: labels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.labels (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    parent_label_name character varying(255) NOT NULL,
    lowest_taxonomic_name character varying(255),
    lowest_aphia_id integer,
    name_is_lowest boolean NOT NULL,
    identification_qualifier character varying(255),
    annotation_set_id uuid NOT NULL,
    CONSTRAINT labels_lowest_aphia_id_adf5a274_check CHECK ((lowest_aphia_id >= 0))
);


--
-- Name: licenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.licenses (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: pis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pis (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: platforms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platforms (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: related_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.related_materials (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    uri character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    relation text NOT NULL
);


--
-- Name: sensors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sensors (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    uri character varying(2048) NOT NULL
);


--
-- Name: annotation_labels annotation_labels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_labels
    ADD CONSTRAINT annotation_labels_pkey PRIMARY KEY (id);


--
-- Name: annotation_set_creators annotation_set_creators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_creators
    ADD CONSTRAINT annotation_set_creators_pkey PRIMARY KEY (id);


--
-- Name: annotation_set_image_sets annotation_set_image_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_image_sets
    ADD CONSTRAINT annotation_set_image_sets_pkey PRIMARY KEY (id);


--
-- Name: annotation_sets annotation_sets_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_sets
    ADD CONSTRAINT annotation_sets_name_key UNIQUE (name);


--
-- Name: annotation_sets annotation_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_sets
    ADD CONSTRAINT annotation_sets_pkey PRIMARY KEY (id);


--
-- Name: annotations annotations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_pkey PRIMARY KEY (id);


--
-- Name: annotators annotators_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotators
    ADD CONSTRAINT annotators_name_key UNIQUE (name);


--
-- Name: annotators annotators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotators
    ADD CONSTRAINT annotators_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: contexts contexts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contexts
    ADD CONSTRAINT contexts_pkey PRIMARY KEY (id);


--
-- Name: creators creators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.creators
    ADD CONSTRAINT creators_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: image_camera_calibration_models image_camera_calibration_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_camera_calibration_models
    ADD CONSTRAINT image_camera_calibration_models_pkey PRIMARY KEY (id);


--
-- Name: image_camera_housing_viewports image_camera_housing_viewports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_camera_housing_viewports
    ADD CONSTRAINT image_camera_housing_viewports_pkey PRIMARY KEY (id);


--
-- Name: image_camera_poses image_camera_poses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_camera_poses
    ADD CONSTRAINT image_camera_poses_pkey PRIMARY KEY (id);


--
-- Name: image_creators image_creators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_creators
    ADD CONSTRAINT image_creators_pkey PRIMARY KEY (id);


--
-- Name: image_domeport_parameters image_domeport_parameters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_domeport_parameters
    ADD CONSTRAINT image_domeport_parameters_pkey PRIMARY KEY (id);


--
-- Name: image_flatport_parameters image_flatport_parameters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_flatport_parameters
    ADD CONSTRAINT image_flatport_parameters_pkey PRIMARY KEY (id);


--
-- Name: image_photometric_calibrations image_photometric_calibrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_photometric_calibrations
    ADD CONSTRAINT image_photometric_calibrations_pkey PRIMARY KEY (id);


--
-- Name: image_set_creators image_set_creators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_creators
    ADD CONSTRAINT image_set_creators_pkey PRIMARY KEY (id);


--
-- Name: image_set_related_materials image_set_related_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_related_materials
    ADD CONSTRAINT image_set_related_materials_pkey PRIMARY KEY (id);


--
-- Name: image_sets image_sets_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_name_key UNIQUE (name);


--
-- Name: image_sets image_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_pkey PRIMARY KEY (id);


--
-- Name: image_sets image_sets_sha256_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_sha256_hash_key UNIQUE (sha256_hash);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: images images_sha256_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_sha256_hash_key UNIQUE (sha256_hash);


--
-- Name: labels labels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.labels
    ADD CONSTRAINT labels_pkey PRIMARY KEY (id);


--
-- Name: licenses licenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_pkey PRIMARY KEY (id);


--
-- Name: pis pis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pis
    ADD CONSTRAINT pis_pkey PRIMARY KEY (id);


--
-- Name: platforms platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT platforms_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: related_materials related_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.related_materials
    ADD CONSTRAINT related_materials_pkey PRIMARY KEY (id);


--
-- Name: sensors sensors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT sensors_pkey PRIMARY KEY (id);


--
-- Name: labels unique_label_name_per_parent; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.labels
    ADD CONSTRAINT unique_label_name_per_parent UNIQUE (name, parent_label_name, annotation_set_id);


--
-- Name: contexts unique_name_uri_api_context; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contexts
    ADD CONSTRAINT unique_name_uri_api_context UNIQUE (name, uri);


--
-- Name: creators unique_name_uri_api_creator; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.creators
    ADD CONSTRAINT unique_name_uri_api_creator UNIQUE (name, uri);


--
-- Name: events unique_name_uri_api_event; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT unique_name_uri_api_event UNIQUE (name, uri);


--
-- Name: licenses unique_name_uri_api_license; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT unique_name_uri_api_license UNIQUE (name, uri);


--
-- Name: pis unique_name_uri_api_pi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pis
    ADD CONSTRAINT unique_name_uri_api_pi UNIQUE (name, uri);


--
-- Name: platforms unique_name_uri_api_platform; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT unique_name_uri_api_platform UNIQUE (name, uri);


--
-- Name: projects unique_name_uri_api_project; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT unique_name_uri_api_project UNIQUE (name, uri);


--
-- Name: sensors unique_name_uri_api_sensor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT unique_name_uri_api_sensor UNIQUE (name, uri);


--
-- Name: related_materials unique_related_material_uri_title_relation; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.related_materials
    ADD CONSTRAINT unique_related_material_uri_title_relation UNIQUE (uri, title, relation);


--
-- Name: annotation_labels uq_annotation_label_annotation_annotator; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_labels
    ADD CONSTRAINT uq_annotation_label_annotation_annotator UNIQUE (label_id, annotation_id, annotator_id);


--
-- Name: annotation_set_creators uq_annotation_set_creator; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_creators
    ADD CONSTRAINT uq_annotation_set_creator UNIQUE (annotation_set_id, creator_id);


--
-- Name: annotation_set_image_sets uq_annotation_set_image_set; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_image_sets
    ADD CONSTRAINT uq_annotation_set_image_set UNIQUE (annotation_set_id, image_set_id);


--
-- Name: image_creators uq_image_creators; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_creators
    ADD CONSTRAINT uq_image_creators UNIQUE (image_id, creator_id);


--
-- Name: images uq_image_filename_image_set; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT uq_image_filename_image_set UNIQUE (filename, image_set_id);


--
-- Name: image_set_creators uq_image_set_creators; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_creators
    ADD CONSTRAINT uq_image_set_creators UNIQUE (image_set_id, creator_id);


--
-- Name: image_set_related_materials uq_image_set_related_materials; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_related_materials
    ADD CONSTRAINT uq_image_set_related_materials UNIQUE (image_set_id, related_material_id);


--
-- Name: annotation_labels_annotation_id_fb3c88ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_labels_annotation_id_fb3c88ae ON public.annotation_labels USING btree (annotation_id);


--
-- Name: annotation_labels_annotator_id_8b67ad6f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_labels_annotator_id_8b67ad6f ON public.annotation_labels USING btree (annotator_id);


--
-- Name: annotation_labels_label_id_74b937ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_labels_label_id_74b937ae ON public.annotation_labels USING btree (label_id);


--
-- Name: annotation_set_creators_annotation_set_id_fa9d5b3c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_set_creators_annotation_set_id_fa9d5b3c ON public.annotation_set_creators USING btree (annotation_set_id);


--
-- Name: annotation_set_creators_creator_id_eaef68cb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_set_creators_creator_id_eaef68cb ON public.annotation_set_creators USING btree (creator_id);


--
-- Name: annotation_set_image_sets_annotation_set_id_7f390f0a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_set_image_sets_annotation_set_id_7f390f0a ON public.annotation_set_image_sets USING btree (annotation_set_id);


--
-- Name: annotation_set_image_sets_image_set_id_d1c70636; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_set_image_sets_image_set_id_d1c70636 ON public.annotation_set_image_sets USING btree (image_set_id);


--
-- Name: annotation_sets_context_id_2977e3b6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_sets_context_id_2977e3b6 ON public.annotation_sets USING btree (context_id);


--
-- Name: annotation_sets_license_id_009cd245; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_sets_license_id_009cd245 ON public.annotation_sets USING btree (license_id);


--
-- Name: annotation_sets_name_8386447c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_sets_name_8386447c_like ON public.annotation_sets USING btree (name varchar_pattern_ops);


--
-- Name: annotation_sets_pi_id_6bbaab5d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_sets_pi_id_6bbaab5d ON public.annotation_sets USING btree (pi_id);


--
-- Name: annotation_sets_project_id_e84bb40d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_sets_project_id_e84bb40d ON public.annotation_sets USING btree (project_id);


--
-- Name: annotations_annotation_set_id_0c704769; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotations_annotation_set_id_0c704769 ON public.annotations USING btree (annotation_set_id);


--
-- Name: annotations_image_id_dbc46831; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotations_image_id_dbc46831 ON public.annotations USING btree (image_id);


--
-- Name: annotators_name_4cb94721_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotators_name_4cb94721_like ON public.annotators USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: image_creators_creator_id_a3ec7299; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_creators_creator_id_a3ec7299 ON public.image_creators USING btree (creator_id);


--
-- Name: image_creators_image_id_9153370e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_creators_image_id_9153370e ON public.image_creators USING btree (image_id);


--
-- Name: image_set_creators_creator_id_f70e74a5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_creators_creator_id_f70e74a5 ON public.image_set_creators USING btree (creator_id);


--
-- Name: image_set_creators_image_set_id_5026a062; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_creators_image_set_id_5026a062 ON public.image_set_creators USING btree (image_set_id);


--
-- Name: image_set_deployment_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_deployment_idx ON public.image_sets USING btree (deployment);


--
-- Name: image_set_fauna_attraction_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_fauna_attraction_idx ON public.image_sets USING btree (fauna_attraction);


--
-- Name: image_set_lat_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_lat_idx ON public.image_sets USING btree (latitude);


--
-- Name: image_set_lon_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_lon_idx ON public.image_sets USING btree (longitude);


--
-- Name: image_set_marine_zone_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_marine_zone_idx ON public.image_sets USING btree (marine_zone);


--
-- Name: image_set_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_name_trgm_idx ON public.image_sets USING gin (name public.gin_trgm_ops);


--
-- Name: image_set_related_materials_image_set_id_cc74b98f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_related_materials_image_set_id_cc74b98f ON public.image_set_related_materials USING btree (image_set_id);


--
-- Name: image_set_related_materials_material_id_2cdf4ec6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_set_related_materials_material_id_2cdf4ec6 ON public.image_set_related_materials USING btree (related_material_id);


--
-- Name: image_sets_camera_calibration_model_id_683a2f7c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_camera_calibration_model_id_683a2f7c ON public.image_sets USING btree (camera_calibration_model_id);


--
-- Name: image_sets_camera_housing_viewport_id_ed132d55; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_camera_housing_viewport_id_ed132d55 ON public.image_sets USING btree (camera_housing_viewport_id);


--
-- Name: image_sets_camera_pose_id_64f2c7df; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_camera_pose_id_64f2c7df ON public.image_sets USING btree (camera_pose_id);


--
-- Name: image_sets_context_id_09e2d2fb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_context_id_09e2d2fb ON public.image_sets USING btree (context_id);


--
-- Name: image_sets_domeport_parameter_id_c00a680d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_domeport_parameter_id_c00a680d ON public.image_sets USING btree (domeport_parameter_id);


--
-- Name: image_sets_event_id_c19e62ca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_event_id_c19e62ca ON public.image_sets USING btree (event_id);


--
-- Name: image_sets_flatport_parameter_id_d19e5d4e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_flatport_parameter_id_d19e5d4e ON public.image_sets USING btree (flatport_parameter_id);


--
-- Name: image_sets_geom_da2c7336_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_geom_da2c7336_id ON public.image_sets USING gist (geom);


--
-- Name: image_sets_license_id_d6d40d8d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_license_id_d6d40d8d ON public.image_sets USING btree (license_id);


--
-- Name: image_sets_limits_3024dead_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_limits_3024dead_id ON public.image_sets USING gist (limits);


--
-- Name: image_sets_name_00883313_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_name_00883313_like ON public.image_sets USING btree (name varchar_pattern_ops);


--
-- Name: image_sets_photometric_calibration_id_57ee2998; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_photometric_calibration_id_57ee2998 ON public.image_sets USING btree (photometric_calibration_id);


--
-- Name: image_sets_pi_id_d8be8830; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_pi_id_d8be8830 ON public.image_sets USING btree (pi_id);


--
-- Name: image_sets_platform_id_0556b0e2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_platform_id_0556b0e2 ON public.image_sets USING btree (platform_id);


--
-- Name: image_sets_project_id_cb8b25fd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_project_id_cb8b25fd ON public.image_sets USING btree (project_id);


--
-- Name: image_sets_sensor_id_bd85448e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_sensor_id_bd85448e ON public.image_sets USING btree (sensor_id);


--
-- Name: image_sets_sha256_hash_b65becc4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_sets_sha256_hash_b65becc4_like ON public.image_sets USING btree (sha256_hash varchar_pattern_ops);


--
-- Name: images_camera_calibration_model_id_2d1f8408; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_camera_calibration_model_id_2d1f8408 ON public.images USING btree (camera_calibration_model_id);


--
-- Name: images_camera_housing_viewport_id_e310cd09; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_camera_housing_viewport_id_e310cd09 ON public.images USING btree (camera_housing_viewport_id);


--
-- Name: images_camera_pose_id_f5d4a58f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_camera_pose_id_f5d4a58f ON public.images USING btree (camera_pose_id);


--
-- Name: images_context_id_e3d92780; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_context_id_e3d92780 ON public.images USING btree (context_id);


--
-- Name: images_deployment_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_deployment_idx ON public.images USING btree (deployment);


--
-- Name: images_domeport_parameter_id_96ebc2ed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_domeport_parameter_id_96ebc2ed ON public.images USING btree (domeport_parameter_id);


--
-- Name: images_event_id_689cc90f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_event_id_689cc90f ON public.images USING btree (event_id);


--
-- Name: images_fauna_attraction_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_fauna_attraction_idx ON public.images USING btree (fauna_attraction);


--
-- Name: images_flatport_parameter_id_40e6c94c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_flatport_parameter_id_40e6c94c ON public.images USING btree (flatport_parameter_id);


--
-- Name: images_geom_c39d1dbf_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_geom_c39d1dbf_id ON public.images USING gist (geom);


--
-- Name: images_image_set_id_3148bfe4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_image_set_id_3148bfe4 ON public.images USING btree (image_set_id);


--
-- Name: images_lat_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_lat_idx ON public.images USING btree (latitude);


--
-- Name: images_license_id_682d4e9b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_license_id_682d4e9b ON public.images USING btree (license_id);


--
-- Name: images_lon_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_lon_idx ON public.images USING btree (longitude);


--
-- Name: images_marine_zone_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_marine_zone_idx ON public.images USING btree (marine_zone);


--
-- Name: images_photometric_calibration_id_0c462188; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_photometric_calibration_id_0c462188 ON public.images USING btree (photometric_calibration_id);


--
-- Name: images_pi_id_17154e55; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_pi_id_17154e55 ON public.images USING btree (pi_id);


--
-- Name: images_platform_id_89c897d9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_platform_id_89c897d9 ON public.images USING btree (platform_id);


--
-- Name: images_project_id_add1891c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_project_id_add1891c ON public.images USING btree (project_id);


--
-- Name: images_sensor_id_ad53359b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_sensor_id_ad53359b ON public.images USING btree (sensor_id);


--
-- Name: images_sha256_hash_a1e50003_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_sha256_hash_a1e50003_like ON public.images USING btree (sha256_hash varchar_pattern_ops);


--
-- Name: labels_annotation_set_id_c5463aac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX labels_annotation_set_id_c5463aac ON public.labels USING btree (annotation_set_id);


--
-- Name: labels_lowest_aphia_id_adf5a274; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX labels_lowest_aphia_id_adf5a274 ON public.labels USING btree (lowest_aphia_id);


--
-- Name: labels_name_f48deff7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX labels_name_f48deff7 ON public.labels USING btree (name);


--
-- Name: labels_name_f48deff7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX labels_name_f48deff7_like ON public.labels USING btree (name varchar_pattern_ops);


--
-- Name: labels_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX labels_name_trgm_idx ON public.labels USING gin (name public.gin_trgm_ops);


--
-- Name: platform_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX platform_name_trgm_idx ON public.platforms USING gin (name public.gin_trgm_ops);


--
-- Name: project_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX project_name_trgm_idx ON public.projects USING gin (name public.gin_trgm_ops);


--
-- Name: annotation_labels annotation_labels_annotation_id_fb3c88ae_fk_annotations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_labels
    ADD CONSTRAINT annotation_labels_annotation_id_fb3c88ae_fk_annotations_id FOREIGN KEY (annotation_id) REFERENCES public.annotations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_labels annotation_labels_annotator_id_8b67ad6f_fk_annotators_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_labels
    ADD CONSTRAINT annotation_labels_annotator_id_8b67ad6f_fk_annotators_id FOREIGN KEY (annotator_id) REFERENCES public.annotators(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_labels annotation_labels_label_id_74b937ae_fk_labels_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_labels
    ADD CONSTRAINT annotation_labels_label_id_74b937ae_fk_labels_id FOREIGN KEY (label_id) REFERENCES public.labels(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_set_creators annotation_set_creat_annotation_set_id_fa9d5b3c_fk_annotatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_creators
    ADD CONSTRAINT annotation_set_creat_annotation_set_id_fa9d5b3c_fk_annotatio FOREIGN KEY (annotation_set_id) REFERENCES public.annotation_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_set_creators annotation_set_creators_creator_id_eaef68cb_fk_creators_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_creators
    ADD CONSTRAINT annotation_set_creators_creator_id_eaef68cb_fk_creators_id FOREIGN KEY (creator_id) REFERENCES public.creators(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_set_image_sets annotation_set_image_annotation_set_id_7f390f0a_fk_annotatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_image_sets
    ADD CONSTRAINT annotation_set_image_annotation_set_id_7f390f0a_fk_annotatio FOREIGN KEY (annotation_set_id) REFERENCES public.annotation_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_set_image_sets annotation_set_image_image_set_id_d1c70636_fk_image_set; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_set_image_sets
    ADD CONSTRAINT annotation_set_image_image_set_id_d1c70636_fk_image_set FOREIGN KEY (image_set_id) REFERENCES public.image_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_sets annotation_sets_context_id_2977e3b6_fk_contexts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_sets
    ADD CONSTRAINT annotation_sets_context_id_2977e3b6_fk_contexts_id FOREIGN KEY (context_id) REFERENCES public.contexts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_sets annotation_sets_license_id_009cd245_fk_licenses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_sets
    ADD CONSTRAINT annotation_sets_license_id_009cd245_fk_licenses_id FOREIGN KEY (license_id) REFERENCES public.licenses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_sets annotation_sets_pi_id_6bbaab5d_fk_pis_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_sets
    ADD CONSTRAINT annotation_sets_pi_id_6bbaab5d_fk_pis_id FOREIGN KEY (pi_id) REFERENCES public.pis(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_sets annotation_sets_project_id_e84bb40d_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_sets
    ADD CONSTRAINT annotation_sets_project_id_e84bb40d_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotations annotations_annotation_set_id_0c704769_fk_annotation_sets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_annotation_set_id_0c704769_fk_annotation_sets_id FOREIGN KEY (annotation_set_id) REFERENCES public.annotation_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotations annotations_image_id_dbc46831_fk_images_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_image_id_dbc46831_fk_images_id FOREIGN KEY (image_id) REFERENCES public.images(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_creators image_creators_creator_id_a3ec7299_fk_creators_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_creators
    ADD CONSTRAINT image_creators_creator_id_a3ec7299_fk_creators_id FOREIGN KEY (creator_id) REFERENCES public.creators(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_creators image_creators_image_id_9153370e_fk_images_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_creators
    ADD CONSTRAINT image_creators_image_id_9153370e_fk_images_id FOREIGN KEY (image_id) REFERENCES public.images(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_set_creators image_set_creators_creator_id_f70e74a5_fk_creators_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_creators
    ADD CONSTRAINT image_set_creators_creator_id_f70e74a5_fk_creators_id FOREIGN KEY (creator_id) REFERENCES public.creators(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_set_creators image_set_creators_image_set_id_5026a062_fk_image_sets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_creators
    ADD CONSTRAINT image_set_creators_image_set_id_5026a062_fk_image_sets_id FOREIGN KEY (image_set_id) REFERENCES public.image_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_set_related_materials image_set_related_ma_image_set_id_cc74b98f_fk_image_set; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_related_materials
    ADD CONSTRAINT image_set_related_ma_image_set_id_cc74b98f_fk_image_set FOREIGN KEY (image_set_id) REFERENCES public.image_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_set_related_materials image_set_related_ma_related_material_id_b77b8a43_fk_related_m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_set_related_materials
    ADD CONSTRAINT image_set_related_ma_related_material_id_b77b8a43_fk_related_m FOREIGN KEY (related_material_id) REFERENCES public.related_materials(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_camera_calibration_m_683a2f7c_fk_image_cam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_camera_calibration_m_683a2f7c_fk_image_cam FOREIGN KEY (camera_calibration_model_id) REFERENCES public.image_camera_calibration_models(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_camera_housing_viewp_ed132d55_fk_image_cam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_camera_housing_viewp_ed132d55_fk_image_cam FOREIGN KEY (camera_housing_viewport_id) REFERENCES public.image_camera_housing_viewports(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_camera_pose_id_64f2c7df_fk_image_camera_poses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_camera_pose_id_64f2c7df_fk_image_camera_poses_id FOREIGN KEY (camera_pose_id) REFERENCES public.image_camera_poses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_context_id_09e2d2fb_fk_contexts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_context_id_09e2d2fb_fk_contexts_id FOREIGN KEY (context_id) REFERENCES public.contexts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_domeport_parameter_i_c00a680d_fk_image_dom; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_domeport_parameter_i_c00a680d_fk_image_dom FOREIGN KEY (domeport_parameter_id) REFERENCES public.image_domeport_parameters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_event_id_c19e62ca_fk_events_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_event_id_c19e62ca_fk_events_id FOREIGN KEY (event_id) REFERENCES public.events(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_flatport_parameter_i_d19e5d4e_fk_image_fla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_flatport_parameter_i_d19e5d4e_fk_image_fla FOREIGN KEY (flatport_parameter_id) REFERENCES public.image_flatport_parameters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_license_id_d6d40d8d_fk_licenses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_license_id_d6d40d8d_fk_licenses_id FOREIGN KEY (license_id) REFERENCES public.licenses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_photometric_calibrat_57ee2998_fk_image_pho; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_photometric_calibrat_57ee2998_fk_image_pho FOREIGN KEY (photometric_calibration_id) REFERENCES public.image_photometric_calibrations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_pi_id_d8be8830_fk_pis_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_pi_id_d8be8830_fk_pis_id FOREIGN KEY (pi_id) REFERENCES public.pis(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_platform_id_0556b0e2_fk_platforms_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_platform_id_0556b0e2_fk_platforms_id FOREIGN KEY (platform_id) REFERENCES public.platforms(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_project_id_cb8b25fd_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_project_id_cb8b25fd_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: image_sets image_sets_sensor_id_bd85448e_fk_sensors_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_sets
    ADD CONSTRAINT image_sets_sensor_id_bd85448e_fk_sensors_id FOREIGN KEY (sensor_id) REFERENCES public.sensors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_camera_calibration_m_2d1f8408_fk_image_cam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_camera_calibration_m_2d1f8408_fk_image_cam FOREIGN KEY (camera_calibration_model_id) REFERENCES public.image_camera_calibration_models(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_camera_housing_viewp_e310cd09_fk_image_cam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_camera_housing_viewp_e310cd09_fk_image_cam FOREIGN KEY (camera_housing_viewport_id) REFERENCES public.image_camera_housing_viewports(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_camera_pose_id_f5d4a58f_fk_image_camera_poses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_camera_pose_id_f5d4a58f_fk_image_camera_poses_id FOREIGN KEY (camera_pose_id) REFERENCES public.image_camera_poses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_context_id_e3d92780_fk_contexts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_context_id_e3d92780_fk_contexts_id FOREIGN KEY (context_id) REFERENCES public.contexts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_domeport_parameter_i_96ebc2ed_fk_image_dom; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_domeport_parameter_i_96ebc2ed_fk_image_dom FOREIGN KEY (domeport_parameter_id) REFERENCES public.image_domeport_parameters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_event_id_689cc90f_fk_events_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_event_id_689cc90f_fk_events_id FOREIGN KEY (event_id) REFERENCES public.events(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_flatport_parameter_i_40e6c94c_fk_image_fla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_flatport_parameter_i_40e6c94c_fk_image_fla FOREIGN KEY (flatport_parameter_id) REFERENCES public.image_flatport_parameters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_image_set_id_3148bfe4_fk_image_sets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_image_set_id_3148bfe4_fk_image_sets_id FOREIGN KEY (image_set_id) REFERENCES public.image_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_license_id_682d4e9b_fk_licenses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_license_id_682d4e9b_fk_licenses_id FOREIGN KEY (license_id) REFERENCES public.licenses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_photometric_calibrat_0c462188_fk_image_pho; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_photometric_calibrat_0c462188_fk_image_pho FOREIGN KEY (photometric_calibration_id) REFERENCES public.image_photometric_calibrations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_pi_id_17154e55_fk_pis_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pi_id_17154e55_fk_pis_id FOREIGN KEY (pi_id) REFERENCES public.pis(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_platform_id_89c897d9_fk_platforms_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_platform_id_89c897d9_fk_platforms_id FOREIGN KEY (platform_id) REFERENCES public.platforms(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_project_id_add1891c_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_project_id_add1891c_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: images images_sensor_id_ad53359b_fk_sensors_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_sensor_id_ad53359b_fk_sensors_id FOREIGN KEY (sensor_id) REFERENCES public.sensors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labels labels_annotation_set_id_c5463aac_fk_annotation_sets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.labels
    ADD CONSTRAINT labels_annotation_set_id_c5463aac_fk_annotation_sets_id FOREIGN KEY (annotation_set_id) REFERENCES public.annotation_sets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

