replicaCount: 1

ingress:
  host: annotations-api.paidiver.site
  path: ""
  tls:
    - secretName: letsencrypt-annotations-api
      hosts:
        - annotations-api.paidiver.site
api:
  workers: 1
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 300m
      memory: 500Mi
  env:
    djangoCorsAllowedOrigins: "https://paidiver.github.io"
    djangoCorsAllowAll: "0"

postgresql:
  primary:
    persistence:
      enabled: true
      size: 2Gi
    resources:
      limits:
        memory: 256Mi
