name: SchemaSpy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  generate:
    uses: paidiver/brokerage-service/.github/workflows/reusable-schemaspy.yml@main
    with:
      database_service: db
      application_service: api
      database_name: annotationsdb
      database_host: db
      excluded_tables: ^(auth_group|auth_group_permissions|auth_permission|auth_user|auth_user_groups|auth_user_user_permissions|authtoken_token|django_admin_log|django_content_type|django_migrations|django_session|spatial_ref_sys|geometry_columns|geography_columns)$
